/*
 * CHAI BAARISH GAANE — playlist.js
 *
 * Runtime track schema:
 *   title, artist, film, year, decade, language, moods, youtubeId
 *
 * A blank youtubeId means that the song is intentionally awaiting the next
 * dedicated YouTube verification pass. IDs are never inferred here.
 */
const cbgSong = (title, artist, film, year, decade, moods = ["romantic"], youtubeId = "", language = "hindi") => ({
  title,
  artist,
  film,
  year,
  decade,
  language,
  moods,
  youtubeId
});

window.CBG_PLAYLIST = [
  /* Evergreen / Older */
  cbgSong("Rimjhim Gire Saawan", "Kishore Kumar", "Manzil", "1979", "70s", ["baarish","romantic","sukoon"], "JQoSSJDZxOo"),
  cbgSong("Bheegi Bheegi Raaton Mein", "Kishore Kumar, Lata Mangeshkar", "Ajanabee", "1974", "70s", ["baarish","romantic","old-gold"], "NkgLsX1Yeec"),
  cbgSong("Pal Pal Dil Ke Paas", "Kishore Kumar", "Blackmail", "1973", "70s", ["romantic","nostalgic"], "AMuRRXCuy-4"),
  cbgSong("Aap Ki Aankhon Mein Kuch", "Kishore Kumar, Lata Mangeshkar", "Ghar", "1978", "70s", ["romantic","sukoon","old-gold"], "daxuKHBWiKE"),
  cbgSong("Neele Neele Ambar Par", "Kishore Kumar", "Kalaakaar", "1983", "80s", ["romantic","shaam","sukoon"], "ThHYiiZTB1Y"),
  cbgSong("Humein Tumse Pyaar Kitna", "Kishore Kumar", "Kudrat", "1981", "80s", ["romantic","sad"], "iTkTrVXwCsA"),
  cbgSong("Kya Mujhe Pyar Hai", "KK", "Woh Lamhe", "2006", "00s", ["romantic","sad"], "Gg6NMU4ivXM"),
  cbgSong("Lag Ja Gale", "Lata Mangeshkar", "Woh Kaun Thi?", "1964", "60s", ["romantic","sad","sukoon"], "br6C4U3Dyfo"),
  cbgSong("Gulabi Aankhen", "Mohammed Rafi", "The Train", "1970", "70s", ["romantic","old-gold"], "KWAdrB2U7cE"),
  cbgSong("Chura Liya Hai Tumne", "Asha Bhosle, Mohammed Rafi", "Yaadon Ki Baaraat", "1973", "70s", ["romantic","old-gold"], "KT0NlItK86A"),
  cbgSong("Pehla Nasha", "Udit Narayan, Sadhana Sargam", "Jo Jeeta Wohi Sikandar", "1992", "90s", ["romantic","nostalgic"], "SBfPs-PMGTA"),
  cbgSong("Ek Ladki Ko Dekha", "Kumar Sanu", "1942: A Love Story", "1994", "90s", ["romantic","nostalgic"], "fTauOK8J-U8"),
  cbgSong("Do Dil Mil Rahe Hain", "Kumar Sanu", "Pardes", "1997", "90s", ["romantic","nostalgic"], "dReDtHKF0-g"),
  cbgSong("Aankhon Mein Base Ho Tum", "Abhijeet, Alka Yagnik", "Takkar", "1995", "90s", ["romantic","nostalgic"], "S1st8FCEgkY"),
  cbgSong("Mera Dil Bhi Kitna Pagal Hai", "Kumar Sanu, Alka Yagnik", "Saajan", "1991", "90s", ["romantic","sad"], "RVQsBlI35vw"),
  cbgSong("Dheere Dheere Se Meri Zindagi Mein Aana", "Kumar Sanu, Anuradha Paudwal", "Aashiqui", "1990", "90s", ["romantic","nostalgic"], "KeyfUuXPOcY"),
  cbgSong("Tujhe Dekha To", "Kumar Sanu, Lata Mangeshkar", "Dilwale Dulhania Le Jayenge", "1995", "90s", ["romantic","safar"], "cNV5hLSa9H8"),
  cbgSong("Aaye Ho Meri Zindagi Mein", "Udit Narayan", "Raja Hindustani", "1996", "90s", ["romantic","nostalgic"], "Mj3KyjuKbqI"),
  cbgSong("Tere Dar Par Sanam", "Kumar Sanu", "Phir Teri Kahani Yaad Aayee", "1993", "90s", ["romantic","sad"], "05o4kCUY2Ys"),
  cbgSong("Bahut Pyar Karte Hain", "Anuradha Paudwal", "Saajan", "1991", "90s", ["romantic","sad"], "ycj1FwxiZwc"),
  cbgSong("Ae Kash Ke Hum", "Kumar Sanu", "Kabhi Haan Kabhi Naa", "1994", "90s", ["romantic","nostalgic"], "Jtg2zyS_y_c"),
  cbgSong("Ghar Se Nikalte Hi", "Udit Narayan", "Papa Kehte Hain", "1996", "90s", ["romantic","nostalgic","safar"], "0NT-xmLX4tk"),

  /* 2000s */
  cbgSong("Zara Zara", "Bombay Jayashri", "Rehnaa Hai Terre Dil Mein", "2001", "00s", ["romantic","baarish","sukoon"], "6CXI5ZQgo7A"),
  cbgSong("Sach Keh Raha Hai Deewana", "KK", "Rehnaa Hai Terre Dil Mein", "2001", "00s", ["sad","romantic"], "kp-Bqr1Gtyw"),
  cbgSong("Dil Ko Tumse Pyaar Hua", "Roop Kumar Rathod", "Rehnaa Hai Terre Dil Mein", "2001", "00s", ["romantic","sukoon"], "XcMy3lyDaQg"),
  cbgSong("Aankhon Mein Teri", "KK", "Om Shanti Om", "2007", "00s", ["romantic","sukoon"], "7KKVb0_IdD4"),
  cbgSong("Ajab Si", "KK", "Om Shanti Om", "2007", "00s", ["romantic","shaam"], "2drIKUOCZxU"),
  cbgSong("Tu Hi Meri Shab Hai", "KK", "Gangster", "2006", "00s", ["romantic","shaam"], "mWBvudKcByg"),
  cbgSong("Labon Ko", "KK", "Bhool Bhulaiyaa", "2007", "00s", ["romantic","shaam"], "XG8XskoJz1I"),
  cbgSong("Beete Lamhein", "KK", "The Train", "2007", "00s", ["sad","nostalgic"], "UlacMvx_VYk"),
  cbgSong("Khuda Jaane", "KK, Shilpa Rao", "Bachna Ae Haseeno", "2008", "00s", ["romantic","safar"], "cmMiyZaSELo"),
  cbgSong("Tujh Mein Rab Dikhta Hai", "Roop Kumar Rathod", "Rab Ne Bana Di Jodi", "2008", "00s", ["romantic","sukoon"], "qoq8B8ThgEM"),
  cbgSong("Haule Haule", "Sukhwinder Singh", "Rab Ne Bana Di Jodi", "2008", "00s", ["romantic","sukoon"], "XgdY_s1LsZc"),
  cbgSong("Main Agar Kahoon", "Sonu Nigam, Shreya Ghoshal", "Om Shanti Om", "2007", "00s", ["romantic","sukoon"], "DAYszemgPxc"),
  cbgSong("Abhi Mujh Mein Kahin", "Sonu Nigam", "Agneepath", "2012", "10s", ["sad","sukoon"], "oWKgpB2zpgw"),
  cbgSong("Suraj Hua Maddham", "Sonu Nigam, Alka Yagnik", "Kabhi Khushi Kabhie Gham", "2001", "00s", ["romantic","sukoon"], "L0zKs8i7Nc8"),
  cbgSong("Kal Ho Naa Ho", "Sonu Nigam", "Kal Ho Naa Ho", "2003", "00s", ["sad","nostalgic"], "g0eO74UmRBs"),
  cbgSong("Main Hoon Na", "Sonu Nigam, Shreya Ghoshal", "Main Hoon Na", "2004", "00s", ["romantic","nostalgic"], "DIJW7rWPkSw"),
  cbgSong("Tumse Milke Dil Ka", "Sonu Nigam, Sabri Brothers", "Main Hoon Na", "2004", "00s", ["romantic"], "mXkbWKr5ovU"),
  cbgSong("Tanhayee", "Sonu Nigam", "Dil Chahta Hai", "2001", "00s", ["sad","nostalgic"], "ZkwaiIGoyT4"),
  cbgSong("Iktara", "Kavita Seth", "Wake Up Sid", "2009", "00s", ["romantic","sukoon"], "fSS_R91Nimw"),
  cbgSong("Tum Se Hi", "Mohit Chauhan", "Jab We Met", "2007", "00s", ["romantic","safar"], "mt9xg0mmt28"),
  cbgSong("Yeh Dooriyan", "Mohit Chauhan", "Love Aaj Kal", "2009", "00s", ["sad","safar"], "kPtn26x8TZM"),
  cbgSong("Masakali", "Mohit Chauhan", "Delhi-6", "2009", "00s", ["safar","sukoon"], "SS3lIQdKP-A"),
  cbgSong("Pee Loon", "Mohit Chauhan", "Once Upon a Time in Mumbaai", "2010", "10s", ["romantic","baarish"], "D8XFTglfSMg"),
  cbgSong("Phir Se Ud Chala", "Mohit Chauhan", "Rockstar", "2011", "10s", ["safar","sukoon"], "2mWaqsC3U7k"),
  cbgSong("Tum Ho", "Mohit Chauhan, Suzanne D'Mello", "Rockstar", "2011", "10s", ["romantic","sukoon"], "VqFn3FvVjk4"),
  cbgSong("Kun Faya Kun", "A.R. Rahman, Javed Ali, Mohit Chauhan", "Rockstar", "2011", "10s", ["sukoon","safar"], "T94PHkuydcw"),
  cbgSong("Tera Hone Laga Hoon", "Atif Aslam, Alisha Chinai", "Ajab Prem Ki Ghazab Kahani", "2009", "00s", ["romantic"], "useznoRhrWU"),
  cbgSong("Pehli Nazar Mein", "Atif Aslam", "Race", "2008", "00s", ["romantic"], "JBCx0QyP8VQ"),
  cbgSong("Tu Jaane Na", "Atif Aslam", "Ajab Prem Ki Ghazab Kahani", "2009", "00s", ["romantic","sad"], "FA_J8XwpCaQ"),
  cbgSong("Tere Liye", "Atif Aslam, Shreya Ghoshal", "Prince", "2010", "10s", ["romantic","sad"], "AlvUuGJccKs"),
  cbgSong("Aadat", "Atif Aslam", "Kalyug", "2005", "00s", ["sad","shaam"], "e5LShHAE03A"),
  cbgSong("Woh Lamhe Woh Baatein", "Atif Aslam", "Zeher", "2005", "00s", ["sad","nostalgic"], "FLKxnL7KwHw"),
  cbgSong("Doorie", "Atif Aslam", "Doorie", "2006", "00s", ["sad","shaam"], "hP2p-yH1tGU"),
  cbgSong("Tere Bin", "Atif Aslam", "Bas Ek Pal", "2006", "00s", ["romantic","sad"], "yIrU21hoHys"),
  cbgSong("Aao Milo Chalo", "Shaan, Ustad Sultan Khan", "Jab We Met", "2007", "00s", ["safar","romantic"], "Mo5tQDcs__g"),
  cbgSong("Jab Se Tere Naina", "Shaan", "Saawariya", "2007", "00s", ["romantic","sukoon"], "3XtUEgQLI5Y"),
  cbgSong("Chand Sifarish", "Shaan, Kailash Kher", "Fanaa", "2006", "00s", ["romantic"], "zWEOx7TSM6I"),
  cbgSong("Kaho Naa Pyaar Hai", "Udit Narayan, Alka Yagnik", "Kaho Naa Pyaar Hai", "2000", "00s", ["romantic","nostalgic"], "-LESbtPT8uw"),
  cbgSong("Na Tum Jaano Na Hum", "Lucky Ali, Ramya", "Kaho Naa Pyaar Hai", "2000", "00s", ["romantic","sukoon"], "eSxo4l-epv8"),
  cbgSong("Ek Pal Ka Jeena", "Lucky Ali", "Kaho Naa Pyaar Hai", "2000", "00s", ["nostalgic"], "aGbPyM6lzBs"),
  cbgSong("Aa Bhi Ja Aa Bhi Ja", "Lucky Ali", "Sur", "2002", "00s", ["romantic","sad","sukoon"], "2OssKfYvVys"),
  cbgSong("Maula Mere Maula", "Roop Kumar Rathod", "Anwar", "2007", "00s", ["romantic","sukoon"], "fxfezWYW39M"),
  cbgSong("Jashn-E-Bahaaraa", "Javed Ali", "Jodhaa Akbar", "2008", "00s", ["romantic","sukoon"], "4h1WFyOQv0Y"),
  cbgSong("Tere Naina", "Shankar Mahadevan, Shreya Ghoshal", "My Name Is Khan", "2010", "10s", ["romantic","sukoon"]),
  cbgSong("Shukran Allah", "Sonu Nigam, Shreya Ghoshal, Salim Merchant", "Kurbaan", "2009", "00s", ["romantic","sukoon"], "z_B0PF8Ug00"),
  cbgSong("Aao Na", "Sadhana Sargam, Udit Narayan", "Kyun! Ho Gaya Na...", "2004", "00s", ["romantic","baarish"], "_TDmRLOqWws"),
  cbgSong("Bol Na Halke Halke", "Rahat Fateh Ali Khan, Mahalakshmi Iyer", "Jhoom Barabar Jhoom", "2007", "00s", ["romantic","sukoon"], "jXwg9l9D51A"),
  cbgSong("Aaj Din Chadheya", "Rahat Fateh Ali Khan", "Love Aaj Kal", "2009", "00s", ["romantic","sukoon"], "lhx8YSbrI6A"),
  cbgSong("Mann Ki Lagan", "Rahat Fateh Ali Khan", "Paap", "2003", "00s", ["romantic","sad"], "jUDP6LmgcCE"),
  cbgSong("O Re Piya", "Rahat Fateh Ali Khan", "Aaja Nachle", "2007", "00s", ["romantic","sukoon"], "iv7lcUkFVSc"),
  cbgSong("Teri Ore", "Rahat Fateh Ali Khan, Shreya Ghoshal", "Singh Is Kinng", "2008", "00s", ["romantic","sukoon"], "GLEx6bhPu7s"),

  /* 2010s */
  cbgSong("Tum Hi Ho", "Arijit Singh", "Aashiqui 2", "2013", "10s", ["romantic","sad"], "81qmmlsIE3k"),
  cbgSong("Chahun Main Ya Naa", "Arijit Singh, Palak Muchhal", "Aashiqui 2", "2013", "10s", ["romantic"], "II7ttbkotA0"),
  cbgSong("Hum Mar Jayenge", "Arijit Singh, Tulsi Kumar", "Aashiqui 2", "2013", "10s", ["romantic","sad"], "ky6nCXpDtlo"),
  cbgSong("Sun Raha Hai", "Ankit Tiwari", "Aashiqui 2", "2013", "10s", ["sad","romantic"], "tQL-gx7PeBc"),
  cbgSong("Agar Tum Saath Ho", "Alka Yagnik, Arijit Singh", "Tamasha", "2015", "10s", ["sad","romantic"], "sK7riqg2mr4"),
  cbgSong("Phir Le Aya Dil", "Arijit Singh", "Barfi!", "2012", "10s", ["romantic","sad","sukoon"], "k6BnSIs3XUQ"),
  cbgSong("Kabira", "Arijit Singh, Harshdeep Kaur", "Yeh Jawaani Hai Deewani", "2013", "10s", ["sad","safar"], "jJ4AsIV1FDI"),
  cbgSong("Ilahi", "Arijit Singh", "Yeh Jawaani Hai Deewani", "2013", "10s", ["safar","sukoon"], "hG7dg7dX4hg"),
  cbgSong("Mast Magan", "Arijit Singh, Chinmayi", "2 States", "2014", "10s", ["romantic","sukoon"], "fXRvluHnjxE"),
  cbgSong("Samjhawan", "Arijit Singh, Shreya Ghoshal", "Humpty Sharma Ki Dulhania", "2014", "10s", ["romantic","sad"], "wO5j3lv_9Fs"),
  cbgSong("Muskurane", "Arijit Singh", "CityLights", "2014", "10s", ["romantic","sad"], "HQ4Ox7mLqds"),
  cbgSong("Hamari Adhuri Kahani", "Arijit Singh", "Hamari Adhuri Kahani", "2015", "10s", ["sad","romantic"], "f3FFOBrMmdg"),
  cbgSong("Khamoshiyan", "Arijit Singh", "Khamoshiyan", "2015", "10s", ["romantic","shaam"], "Mv3SZDP7QUo"),
  cbgSong("Soch Na Sake", "Arijit Singh, Tulsi Kumar", "Airlift", "2016", "10s", ["romantic","sad"], "MRtRcTfszjY"),
  cbgSong("Ae Dil Hai Mushkil", "Arijit Singh", "Ae Dil Hai Mushkil", "2016", "10s", ["sad","romantic"], "6FURuLYrR_Q"),
  cbgSong("Channa Mereya", "Arijit Singh", "Ae Dil Hai Mushkil", "2016", "10s", ["sad","sukoon"], "284Ov7ysmfA"),
  cbgSong("Enna Sona", "Arijit Singh", "OK Jaanu", "2017", "10s", ["romantic","sukoon"], "mrdRHsIkK_c"),
  cbgSong("Hawayein", "Arijit Singh", "Jab Harry Met Sejal", "2017", "10s", ["romantic","safar"], "lBACSadCKaQ"),
  cbgSong("Phir Bhi Tumko Chaahunga", "Arijit Singh, Shashaa Tirupati", "Half Girlfriend", "2017", "10s", ["romantic","sad"], "cO02qJw6skA"),
  cbgSong("Qaafirana", "Arijit Singh, Nikhita Gandhi", "Kedarnath", "2018", "10s", ["romantic","safar"], "ZmcBC9-wAXM"),
  cbgSong("Ve Maahi", "Arijit Singh, Asees Kaur", "Kesari", "2019", "10s", ["romantic","sukoon"], "j6muwUGdvXw"),
  cbgSong("Tera Yaar Hoon Main", "Arijit Singh", "Sonu Ke Titu Ki Sweety", "2018", "10s", ["nostalgic","sad"], "EatzcaVJRMs"),
  cbgSong("Kaise Mujhe", "Benny Dayal, Shreya Ghoshal", "Ghajini", "2008", "00s", ["romantic","sad"], "OJVKIvKFmWk"),
  cbgSong("Saibo", "Shreya Ghoshal, Tochi Raina", "Shor in the City", "2011", "10s", ["romantic","sukoon"], "GtNrQy90Ih4"),
  cbgSong("Bahara", "Shreya Ghoshal, Sona Mohapatra", "I Hate Luv Storys", "2010", "10s", ["romantic","sukoon"], "7N74i_rAfFE"),
  cbgSong("Manwa Laage", "Shreya Ghoshal, Arijit Singh", "Happy New Year", "2014", "10s", ["romantic"], "d8IT-16kA8M"),
  cbgSong("Zehnaseeb", "Chinmayi, Shekhar Ravjiani", "Hasee Toh Phasee", "2014", "10s", ["romantic","sukoon"], "KLYwt0YmQw8"),
  cbgSong("Ishq Wala Love", "Shekhar Ravjiani, Salim Merchant, Neeti Mohan", "Student of the Year", "2012", "10s", ["romantic","sukoon"], "VmH8tELQ3aE"),
  cbgSong("Naina", "Arijit Singh", "Dangal", "2016", "10s", ["sad","nostalgic"], "yXbeYaVQ8JY"),
  cbgSong("Jiyein Kyun", "Papon", "Dum Maaro Dum", "2011", "10s", ["sad","shaam"], "sJW37INWnYk"),
  cbgSong("Moh Moh Ke Dhaage", "Papon, Monali Thakur", "Dum Laga Ke Haisha", "2015", "10s", ["romantic","sukoon"]),
  cbgSong("Kaun Mera", "Papon", "Special 26", "2013", "10s", ["romantic","sad"], "j8naefuRSbA"),
  cbgSong("Humnava", "Papon", "Hamari Adhuri Kahani", "2015", "10s", ["sad","romantic"], "ktPD6TMovxs"),
  cbgSong("Tu Kisi Rail Si", "Swanand Kirkire", "Masaan", "2015", "10s", ["romantic","sukoon"], "bKyhc18RCho"),
  cbgSong("Ikk Kudi", "Shahid Mallya", "Udta Punjab", "2016", "10s", ["sad","sukoon"], "cyKZXbxx2lc"),
  cbgSong("Dariya", "Arko", "Baar Baar Dekho", "2016", "10s", ["romantic","sukoon"], "C16EMv_J02w"),
  cbgSong("Nazm Nazm", "Arko", "Bareilly Ki Barfi", "2017", "10s", ["romantic","sukoon"], "RFx4g4GunYw"),
  cbgSong("Kho Gaye Hum Kahan", "Jasleen Royal, Prateek Kuhad", "Baar Baar Dekho", "2016", "10s", ["nostalgic","sukoon"], "as6gP05d_d4"),
  cbgSong("Ranjha", "B Praak, Jasleen Royal", "Shershaah", "2021", "20s", ["romantic","sad"], "V7LwfY5U5WI"),
  cbgSong("Baarish", "Ash King, Shashaa Tirupati", "Half Girlfriend", "2017", "10s", ["baarish","romantic"], "u6p6dubzHAc"),
  cbgSong("Baarish", "Mohammed Irfan, Gajendra Verma", "Yaariyan", "2014", "10s", ["baarish","romantic"], "IA2SN1QQbp8"),
  cbgSong("Sawan Aaya Hai", "Arijit Singh", "Creature 3D", "2014", "10s", ["baarish","romantic"], "UPxKI6pgyBQ"),
  cbgSong("Kabhi Jo Baadal Barse", "Arijit Singh", "Jackpot", "2013", "10s", ["baarish","romantic","sad"], "CXxkOAE1gPw"),
  cbgSong("Dekha Hazaro Dafaa", "Arijit Singh, Palak Muchhal", "Rustom", "2016", "10s", ["romantic","sukoon"], "NzijbnP6B0w"),

  /* Newer */
  cbgSong("Apna Bana Le", "Arijit Singh", "Bhediya", "2022", "20s", ["romantic","sukoon"], "3pz_bHeZLkg"),
  cbgSong("O Maahi", "Arijit Singh", "Dunki", "2023", "20s", ["romantic","safar"], "Etkd-07gnxM"),
  cbgSong("Sajni", "Arijit Singh", "Laapataa Ladies", "2024", "20s", ["romantic","sad"], "k3g_WjLCsXM"),
  cbgSong("Tere Vaaste", "Varun Jain, Sachin-Jigar, Shadab Faridi, Altamash Faridi", "Zara Hatke Zara Bachke", "2023", "20s", ["romantic"], "g5WZLO8BAC8"),
  cbgSong("Chaleya", "Arijit Singh, Shilpa Rao", "Jawan", "2023", "20s", ["romantic","sukoon"], "VAdGW7QDJiU"),
  cbgSong("Tere Hawaale", "Arijit Singh, Shilpa Rao", "Laal Singh Chaddha", "2022", "20s", ["romantic","sad"], "KUpwupYj_tY"),
  cbgSong("Phir Aur Kya Chahiye", "Arijit Singh", "Zara Hatke Zara Bachke", "2023", "20s", ["romantic","sukoon"], "PR_mFnjFidk"),
  cbgSong("Akhiyaan Gulaab", "Mitraz", "Teri Baaton Mein Aisa Uljha Jiya", "2024", "20s", ["romantic"], "r-BAhGM-dmA"),
  cbgSong("Husn", "Anuv Jain", "Husn", "2023", "20s", ["romantic","sad","sukoon"], "gJLVTKhTnog"),
  cbgSong("Jo Tum Mere Ho", "Anuv Jain", "Jo Tum Mere Ho", "2024", "20s", ["romantic","sukoon"], "ilNt2bikxDI"),
  cbgSong("Aankhon Se Batana", "Dikshant", "Aankhon Se Batana", "2022", "20s", ["romantic","sukoon"], "2vKMY75kvjI"),
  cbgSong("Kasoor", "Prateek Kuhad", "Kasoor", "2020", "20s", ["romantic","sad","sukoon"], "BmUe3-sfr7E"),
  cbgSong("Baarishein", "Anuv Jain", "Baarishein", "2018", "10s", ["baarish","romantic","sukoon"], "PJWemSzExXs"),
  cbgSong("Alag Aasmaan", "Anuv Jain", "Alag Aasmaan", "2020", "20s", ["safar","sad","sukoon"], "vA86QFrXoho"),
  cbgSong("Gul", "Anuv Jain", "Gul", "2021", "20s", ["romantic","sad","sukoon"], "SmaY7RfBgas"),
  cbgSong("Kahani Suno 2.0", "Kaifi Khalil", "Kahani Suno 2.0", "2022", "20s", ["romantic","sad"], "_XBVWlI8TsQ"),
  cbgSong("Heeriye", "Jasleen Royal, Arijit Singh", "Heeriye", "2023", "20s", ["romantic","sukoon"], "RLzC55ai0eo"),
  cbgSong("O Bedardeya", "Arijit Singh", "Tu Jhoothi Main Makkaar", "2023", "20s", ["sad","romantic"], "EdftT8GMU1U"),
  cbgSong("Arz Kiya Hai", "Anuv Jain", "Arz Kiya Hai - Coke Studio Bharat", "2025", "20s", ["romantic","sukoon"], "bP8ATWCvqzw"),
  cbgSong("Bairan", "Banjaare", "Bairan", "2026", "20s", ["sad","sukoon"], "oafxkMv4xnc"),

  /* Additional Romantic / 90s–2000s */
  cbgSong("Tune Zindagi Mein", "Udit Narayan", "Humraaz", "2002", "00s", ["romantic","sad"], "PjYSNHGbERs"),
  cbgSong("Hum Apni Taraf Se", "Kumar Sanu, Alka Yagnik", "Ansh: The Deadly Part", "2002", "00s", ["romantic","sad"], "6KTS5HpwK0E"),
  cbgSong("Jo Bhi Kasmein", "Udit Narayan, Alka Yagnik", "Raaz", "2002", "00s", ["romantic","sad"], "Mje4yC8NG_s"),
  cbgSong("Kitna Pyaara Hai", "Udit Narayan, Alka Yagnik", "Raaz", "2002", "00s", ["romantic"], "fPgBPqdR7-c"),
  cbgSong("Main Agar Saamne", "Abhijeet, Alka Yagnik", "Raaz", "2002", "00s", ["romantic","sad"], "KtqPRxTAbYQ"),
  cbgSong("Itna Main Chaahun Tujhe", "Udit Narayan, Alka Yagnik", "Raaz", "2002", "00s", ["romantic","sad"], "hR8AUj1J3kk"),
  cbgSong("Din Ne Ye Kaha Hai Dil Se", "Udit Narayan, Alka Yagnik", "Dhadkan", "2000", "00s", ["romantic","sad"], "ze9EhyeE9-4"),
  cbgSong("Dulhe Ka Sehra", "Nusrat Fateh Ali Khan", "Dhadkan", "2000", "00s", ["romantic","nostalgic"], "iZAv9zDeFSc"),
  cbgSong("Aksar Is Duniya Mein", "Alka Yagnik", "Dhadkan", "2000", "00s", ["romantic","nostalgic"], "-u1YYyRmmsc"),
  cbgSong("Resham Si Hain Yeh Hawayein", "Udit Narayan", "Mere Yaar Ki Shaadi Hai", "2002", "00s", ["romantic","sukoon"]),
  cbgSong("Ek Ladki Ki Tumhe", "Udit Narayan, Alka Yagnik", "Mere Yaar Ki Shaadi Hai", "2002", "00s", ["romantic"], "QaOe6GKw5Ic"),
  cbgSong("Mere Yaar Ki Shaadi Hai", "Udit Narayan, Sonu Nigam, Alka Yagnik", "Mere Yaar Ki Shaadi Hai", "2002", "00s", ["romantic","nostalgic"], "guHHhEUYAQ4"),
  cbgSong("Taaron Ka Chamakta Gehna Ho", "Bali Brahmbhatt, Udit Narayan", "Hum Tumhare Hain Sanam", "2002", "00s", ["romantic","nostalgic"], "GN8pRrHdzHY"),
  cbgSong("Taal Se Taal Mila", "Alka Yagnik, Udit Narayan", "Taal", "1999", "90s", ["romantic","baarish"], "dfghBD0hC9I"),
  cbgSong("Pehli Pehli Baar", "Kumar Sanu, Alka Yagnik", "Sirf Tum", "1999", "90s", ["romantic","nostalgic"], "cBGDDBHN22U"),
  cbgSong("Dilbar Dilbar", "Alka Yagnik", "Sirf Tum", "1999", "90s", ["romantic","nostalgic"], "KvWylZjOrYs"),
  cbgSong("Panchhi Sur Mein Gaate Hain", "Udit Narayan", "Sirf Tum", "1999", "90s", ["romantic","sukoon"], "Fl4ieJvjC60"),
  cbgSong("Ek Mulaqat Zaroori Hai", "Sabri Brothers", "Sirf Tum", "1999", "90s", ["romantic","sad"], "qKpnmFiCTSY"),
  cbgSong("Tere Naam", "Udit Narayan, Alka Yagnik", "Tere Naam", "2003", "00s", ["romantic","sad"], "OMoU0Pfibc4"),
  cbgSong("Tere Naam (Sad Version)", "Udit Narayan", "Tere Naam", "2003", "00s", ["sad","romantic"], "L7r_roRQMl8"),
  cbgSong("Tune Saath Jo Mera Chhoda", "Udit Narayan, Raghav", "Tere Naam", "2003", "00s", ["sad","romantic"], "F5KtNSMRAfM"),
  cbgSong("Kyon Kisi Ko", "Udit Narayan", "Tere Naam", "2003", "00s", ["sad"], "iCZfjggJg3M"),
  cbgSong("Man Basia", "Alka Yagnik", "Tere Naam", "2003", "00s", ["romantic","sukoon"], "7v5F-t1z5ts"),
  cbgSong("Galliyan", "Ankit Tiwari", "Ek Villain", "2014", "10s", ["romantic","sad"], "FxAG_11PzCk"),
  cbgSong("Banjaara", "Mohammed Irfan", "Ek Villain", "2014", "10s", ["romantic","sad"], "0NFxcNheoLc"),
  cbgSong("Zaroorat", "Mustafa Zahid", "Ek Villain", "2014", "10s", ["sad"], "VMEXKJbsUmE"),
  cbgSong("To Phir Aao", "Mustafa Zahid", "Awarapan", "2007", "00s", ["sad","romantic"], "h5-Kq9k3zeo"),
  cbgSong("Tera Mera Rishta", "Mustafa Zahid", "Awarapan", "2007", "00s", ["sad","romantic"], "0J0HZrDvbjY"),
  cbgSong("Kaun Tujhe", "Palak Muchhal", "M.S. Dhoni: The Untold Story", "2016", "10s", ["romantic","sad"], "atVof3pjT-I"),
  cbgSong("Saari Raat Teri Yaad", "Udit Narayan, Alka Yagnik", "Footpath", "2003", "00s", ["romantic","sad"], "1KvCHSlK9vc"),
  cbgSong("Zara Dekh Mera Deewanapan", "Udit Narayan, Alka Yagnik", "Footpath", "2003", "00s", ["romantic","sad"], "iDrNusV2bE8"),
  cbgSong("Falak Tak Chal Saath Mere", "Udit Narayan, Mahalakshmi Iyer", "Tashan", "2008", "00s", ["romantic","safar"], "vr8RaNuWjWc"),
  cbgSong("Jeena Sirf Mere Liye", "Babul Supriyo, Alka Yagnik", "Jeena Sirf Merre Liye", "2002", "00s", ["romantic","sad"], "I6pJI0JF8EA"),

  /* Emraan Hashmi-associated songs */
  cbgSong("Dil Ibadat", "KK", "Tum Mile", "2009", "00s", ["romantic","sad"], "bCgBLKPE35Y"),
  cbgSong("Deewana Kar Raha Hai", "Javed Ali", "Raaz 3", "2012", "10s", ["romantic","sad"], "uIvZHM9J-Rw"),
  cbgSong("Zara Sa", "KK", "Jannat", "2008", "00s", ["romantic","shaam"], "ZsAOnmByy38"),
  cbgSong("Woh Lamhe", "Atif Aslam", "Jal Pari", "2004", "00s", ["sad","nostalgic"]),
  cbgSong("Haal-E-Dil", "Harshit Saxena", "Murder 2", "2011", "10s", ["sad","romantic"], "acdKE2hja7w"),
  cbgSong("Phir Mohabbat", "Mohammed Irfan, Arijit Singh, Saim Bhat", "Murder 2", "2011", "10s", ["sad","romantic"], "v71SiUe0KYY"),
  cbgSong("Haan Tu Hai", "KK", "Jannat", "2008", "00s", ["romantic","sad"], "V1fbOsHBlZE"),
  cbgSong("Tu Hi Haqeeqat", "Javed Ali", "Tum Mile", "2009", "00s", ["romantic","sad"], "BKbnmLH8UAo"),

  /* Tumsa Nahin Dekha */
  cbgSong("Bheed Mein", "Udit Narayan, Shreya Ghoshal", "Tumsa Nahin Dekha: A Love Story", "2004", "00s", ["romantic","sad"], "Eu9LPo0gqeQ"),
  cbgSong("Woh Humse Khafa Hain", "Udit Narayan, Shreya Ghoshal", "Tumsa Nahin Dekha: A Love Story", "2004", "00s", ["romantic","sad"], "JkAifHDj0fE"),
  cbgSong("Dhanak Ka Rang", "Shreya Ghoshal", "Tumsa Nahin Dekha: A Love Story", "2004", "00s", ["romantic","sukoon"], "hYKY4oLbs2Q"),

  /* Additional Classics */
  cbgSong("Bulleya", "Amit Mishra, Shilpa Rao", "Ae Dil Hai Mushkil", "2016", "10s", ["sad","romantic"], "wTgrZE9RWNY"),
  cbgSong("Aaj Mausam Bada Beimaan Hai", "Mohammed Rafi", "Loafer", "1973", "70s", ["old-gold","baarish","nostalgic"], "opABbsJaRLQ"),
  cbgSong("Mere Samne Wali Khidki Mein", "Kishore Kumar", "Padosan", "1968", "60s", ["romantic","old-gold"], "XINI9JtypMw"),
  cbgSong("Yeh Raaten Yeh Mausam", "Asha Bhosle, Kishore Kumar", "Dilli Ka Thug", "1958", "50s", ["romantic","shaam","old-gold"], "ouNb2s33ioQ"),

  /* Kasoor — complete original soundtrack */
  cbgSong("Zindagi Ban Gaye Ho Tum", "Alka Yagnik, Udit Narayan", "Kasoor", "2001", "00s", ["romantic","sukoon"], "gejEimJIdWc"),
  cbgSong("Koi To Saathi Chahiye", "Kumar Sanu", "Kasoor", "2001", "00s", ["romantic","sad"], "9ylzcAwzROs"),
  cbgSong("Dil Mera Tod Diya", "Alka Yagnik", "Kasoor", "2001", "00s", ["sad"], "TuxveFT--1U"),
  cbgSong("Kal Raat Ho Gayee", "Alka Yagnik, Kumar Sanu", "Kasoor", "2001", "00s", ["romantic","shaam"], "u5JIUfrpzY8"),
  cbgSong("Kitni Bechain Hoke", "Alka Yagnik, Udit Narayan", "Kasoor", "2001", "00s", ["romantic"], "ZHcxorEN7k4"),
  cbgSong("Mohabbat Ho Na Jaye (Dekha Jo Tumko)", "Alka Yagnik, Kumar Sanu", "Kasoor", "2001", "00s", ["romantic","sukoon"], "SbnpXVOzf6g"),

  /* Muskaan — complete original soundtrack */
  cbgSong("Ishq Hasata Hai", "Sonu Nigam, Anuradha Paudwal", "Muskaan", "2003", "00s", ["romantic","sad"], "p5jvLT7wod4"),
  cbgSong("Jaaneman Chupke Chupke", "Udit Narayan, Alka Yagnik", "Muskaan", "2003", "00s", ["romantic"], "FNImjHOLS_E"),
  cbgSong("Jaaneman Chupke Chupke-2", "Anuradha Paudwal", "Muskaan", "2003", "00s", ["romantic","sukoon"], "RA8iE6XwI7E"),
  cbgSong("Jis Din Teri Meri Baatein", "Udit Narayan, Anuradha Paudwal", "Muskaan", "2003", "00s", ["romantic"], "o2ZrGUWiavY"),
  cbgSong("Kabhie Jaage Soye", "Udit Narayan, Anuradha Paudwal", "Muskaan", "2003", "00s", ["romantic","sukoon"], "CnIqESltgwA"),
  cbgSong("Nach Punjaban Nachle", "Sonu Nigam, Anuradha Paudwal", "Muskaan", "2003", "00s", ["romantic","nostalgic"], "petIS6mS-0o"),
  cbgSong("Nami Danam", "Shaan, Alka Yagnik", "Muskaan", "2003", "00s", ["romantic","sukoon"], "6DK0htUj_Us"),
  cbgSong("Woh Ho Tum", "Sonu Nigam, Anuradha Paudwal", "Muskaan", "2003", "00s", ["romantic"], "LCl2_jiPtpg"),
  cbgSong("Woh Ho Tum", "Sonu Nigam, Shreya Ghoshal", "Muskaan", "2003", "00s", ["romantic","sukoon"], "utTZFVaQnlA"),
  cbgSong("Woh Ho Tum (Sad)", "Sonu Nigam", "Muskaan", "2003", "00s", ["sad","romantic"], "tALSTPQUMf8"),
  cbgSong("Yaad Aayee", "Adnan Sami", "Muskaan", "2003", "00s", ["sad","nostalgic"], "9AgIuLJ33lY"),

  /* =========================================================================
   * KANNADA PLAYLIST (101 VERIFIED UNIQUE RECORDINGS)
   * Source: Independent Verification Report
   * ========================================================================= */

  /* Kannada Classics & 1970s–1980s */
  cbgSong("Nee Mudida Mallige", "P. B. Sreenivos, P. Susheela", "Gandhinagara", "1968", "60s", ["romantic","old-gold","sukoon"], "ruWm5ymTqTc", "kannada"),
  cbgSong("Nee Bandu Ninthaaga", "P. B. Sreenivos, P. Susheela", "Kasturi Nivasa", "1971", "70s", ["nostalgic","old-gold","sukoon"], "uxd99hWcCwk", "kannada"),
  cbgSong("Naa Ninna Mareyalaare", "Dr. Rajkumar, Vani Jairam", "Naa Ninna Mareyalaare", "1976", "70s", ["romantic","old-gold","nostalgic"], "FD3UN6dELZg", "kannada"),
  cbgSong("Nagunagutha Nee Baruve", "Dr. Rajkumar, S. Janaki", "Giri Kanye", "1977", "70s", ["romantic","old-gold","sukoon"], "8M0VCvCEZt0", "kannada"),
  cbgSong("Sangeethave Nee Nudiyuva Maathella", "P. B. Sreenivos, S. Janaki", "Olavu Gelavu", "1977", "70s", ["romantic","old-gold","shaam"], "fWEnOMqpm_k", "kannada"),
  cbgSong("Chinnada Mallige Hoove", "Dr. Rajkumar, S. Janaki", "Huliya Haalina Mevu", "1979", "70s", ["romantic","old-gold","sukoon"], "HxACdiw_bzg", "kannada"),
  cbgSong("Kaalavannu Thadeyoru Yaaru", "K. J. Yesudas", "Kittu Puttu", "1977", "70s", ["nostalgic","old-gold","shaam"], "sITjP88pkso", "kannada"),
  cbgSong("Naguva Nayana", "S. P. Balasubrahmanyam, S. Janaki", "Pallavi Anu Pallavi", "1983", "80s", ["romantic","sukoon","old-gold","shaam"], "AJSeaFthdeE", "kannada"),
  cbgSong("Ee Roopave Shaapa Venu", "S. P. Balasubrahmanyam", "Seetha Ramu", "1979", "70s", ["sad","old-gold","nostalgic"], "2tkSl2VAaXo", "kannada"),
  cbgSong("Nammooru Mysooru", "S. P. Balasubrahmanyam, S. Janaki", "Preethi Maadu Tamasshe Nodu", "1979", "70s", ["nostalgic","old-gold","safar"], "0GitJfefbGg", "kannada"),

  /* Kannada 1990s */
  cbgSong("Mutthu Mutthu Neera Haniya", "S. P. Balasubrahmanyam, K. S. Chithra", "Nammoora Mandara Hoove", "1996", "90s", ["baarish","romantic","nostalgic","sukoon"], "nWzfR3ZYU7k", "kannada"),
  cbgSong("Ee Sundara Beladingala", "S. P. Balasubrahmanyam, K. S. Chithra", "Amruthavarshini", "1997", "90s", ["romantic","sukoon","shaam","baarish"], "1mY9GP17p5Y", "kannada"),
  cbgSong("O Gulabiye", "Dr. Rajkumar", "Om", "1995", "90s", ["sad","nostalgic","romantic"], "gUpu89jDTwI", "kannada"),
  cbgSong("Suvvi Suvvi Saviyaada", "S. P. Balasubrahmanyam", "Laali", "1997", "90s", ["sukoon","nostalgic"], "Qncab3uQu9w", "kannada"),
  cbgSong("Muddina Hudugi Chanda", "S. P. Balasubrahmanyam, K. S. Chithra", "Rayaru Bandaru Mavana Manege", "1993", "90s", ["romantic","nostalgic"], "0BNwT6J9PoA", "kannada"),
  cbgSong("Sum Sumne", "L. N. Shastry", "A", "1998", "90s", ["romantic","nostalgic","sukoon"], "1cPSG6Lb0v8", "kannada"),
  cbgSong("Nooru Janmaku", "Rajesh Krishnan", "America America", "1997", "90s", ["romantic","nostalgic","sukoon","safar"], "pFt58gtRgiM", "kannada"),

  /* Kannada 2000s */
  cbgSong("Olave Nannolave", "Sonu Nigam", "Laali Haadu", "2003", "00s", ["romantic","sukoon","nostalgic"], "Wks8AXdywpI", "kannada"),
  cbgSong("Ee Nanna Kannane", "Gurukiran, Nanditha", "Abhi", "2003", "00s", ["romantic","sukoon"], "wjExnvtEpZQ", "kannada"),
  cbgSong("O Manase Manase", "K. J. Yesudas", "Gaja", "2008", "00s", ["sad","sukoon","shaam"], "ygaF8EALGkM", "kannada"),
  cbgSong("Hoo Kanasa Jokali", "Sonu Nigam", "Inthi Ninna Preethiya", "2008", "00s", ["sad","sukoon","nostalgic","shaam"], "Fi1WmAMKkhY", "kannada"),
  cbgSong("Kuch Kuch Anthide", "Krishna Beura, Sunitha", "Raaj The Showman", "2009", "00s", ["romantic","sukoon","shaam"], "VZe3bLfdL-c", "kannada"),
  cbgSong("Avala Olave Chandu", "Rajesh Krishnan", "Chandu", "2002", "00s", ["romantic","sukoon"], "dSpesnqMuaM", "kannada"),
  cbgSong("Anisuthide", "Sonu Nigam", "Mungaru Male", "2006", "00s", ["baarish","sukoon","romantic","shaam"], "uchdYcbq7Ys", "kannada"),
  cbgSong("Madhura Pisumatige", "Mohit Chauhan, Shamitha Malnad", "Birugaali", "2009", "00s", ["romantic","sukoon","safar","shaam"], "nsVTVikFCOA", "kannada"),
  cbgSong("Aramage Idde Naanu", "Sonu Nigam, Shreya Ghoshal", "Gokula", "2009", "00s", ["romantic","sukoon","safar"], "mIRkDPbd-x4", "kannada"),
  cbgSong("Araluthiru", "Shreya Ghoshal", "Mungaru Male", "2006", "00s", ["baarish","romantic","sukoon","shaam"], "2dmEEpGeqlo", "kannada"),
  cbgSong("Ivanu Geleyanalla", "Shreya Ghoshal", "Mungaru Male", "2006", "00s", ["romantic","sad","baarish","sukoon"], "yscPvhg8CGc", "kannada"),
  cbgSong("Ninnindale Ninnindale", "Sonu Nigam", "Milana", "2007", "00s", ["romantic","sukoon","safar","nostalgic"], "-xmRjO2G05c", "kannada"),
  cbgSong("Mungaru Maleye", "Sonu Nigam", "Mungaru Male", "2006", "00s", ["baarish","nostalgic","sukoon","shaam"], "Fz6zKCrV2vg", "kannada"),
  cbgSong("Nee Sanihake Bandre", "Sonu Nigam", "Maleyali Jotheyali", "2009", "00s", ["baarish","romantic","sukoon","shaam"], "Q-Eeacn-7aI", "kannada"),
  cbgSong("Ee Sanje Yaakagide", "Sonu Nigam", "Geleya", "2007", "00s", ["shaam","sukoon","romantic","sad"], "ivZYiVirkKc", "kannada"),
  cbgSong("Nee Nenedare", "Sonu Nigam", "Junglee", "2009", "00s", ["romantic","sukoon","baarish"], "ff3PgNcC_eY", "kannada"),
  cbgSong("Kavithe Kavithe", "Vijay Prakash", "Gaalipata", "2008", "00s", ["romantic","sukoon","shaam","nostalgic"], "kPOxhJPGBs4", "kannada"),

  /* Kannada 2010s */
  cbgSong("Sadaa Ninna Kannali", "Sonu Nigam, Shreya Ghoshal", "Bachchan", "2013", "10s", ["romantic","sukoon","shaam"], "lnVeVAvOojA", "kannada"),
  cbgSong("Ninna Snehadinda", "Shreya Ghoshal", "Mugulu Nage", "2017", "10s", ["sukoon","romantic","shaam","nostalgic"], "LeWQ1dyL658", "kannada"),
  cbgSong("Ondu Malebillu", "Armaan Malik, Shreya Ghoshal", "Chakravarthy", "2017", "10s", ["baarish","romantic","sukoon"], "Xv1NQFN9Kd8", "kannada"),
  cbgSong("Belageddu", "Vijay Prakash", "Kirik Party", "2016", "10s", ["sukoon","safar","nostalgic"], "ebz20FHrT44", "kannada"),
  cbgSong("Kareyole", "Inchara Rao", "Rangitaranga", "2015", "10s", ["baarish","sukoon","nostalgic","shaam"], "54VIJ2jomMc", "kannada"),
  cbgSong("Roopasi Sumsumne", "Vijay Prakash", "Mugulu Nage", "2017", "10s", ["romantic","sukoon","shaam"], "7TJN6kNDxQ8", "kannada"),
  cbgSong("Usire Usire", "Shaan, Shreya Ghoshal", "Hebbuli", "2017", "10s", ["romantic","sukoon","shaam"], "ObydPjLF4iM", "kannada"),
  cbgSong("Bombe Helutaithe", "Vijay Prakash", "Raajakumara", "2017", "10s", ["nostalgic","sukoon","old-gold"], "fpGvB7AT1vA", "kannada"),
  cbgSong("Sidila Bharava", "Ananya Bhat, Ravi Basrur", "K.G.F: Chapter 1", "2018", "10s", ["safar"], "itZimRsBW6I", "kannada"),
  cbgSong("Hey Who Are You", "Bharath B. J.", "Kirik Party", "2016", "10s", ["safar"], "ps3FPq0hlG8", "kannada"),
  cbgSong("Sojugada Soojumallige", "Ananya Bhat", "Sounds of Isha", "2019", "10s", ["sukoon","nostalgic","shaam","old-gold"], "gTk-xB3GSOg", "kannada"),
  cbgSong("Gaganave Baagi", "Shreya Ghoshal", "Sanju Weds Geetha", "2011", "10s", ["romantic","baarish","sukoon","shaam"], "XTIwUF7Yrqs", "kannada"),
  cbgSong("Modala Maleyanthe", "Sonu Nigam, Shreya Ghoshal", "Mynaa", "2013", "10s", ["baarish","romantic","sukoon"], "pm0iMhkSe-o", "kannada"),
  cbgSong("Ninneya Nalumeya", "Shreya Ghoshal", "Pancharangi", "2010", "10s", ["romantic","sukoon","shaam"], "Pt1e68xoCxQ", "kannada"),
  cbgSong("Aalochane", "Shreya Ghoshal", "Romeo", "2012", "10s", ["romantic","sukoon"], "aGGyYYmfzTU", "kannada"),
  cbgSong("Yenendu Hesaridali", "Sonu Nigam, Shreya Ghoshal", "Anna Bond", "2012", "10s", ["romantic","sukoon","shaam"], "A6AwVskOCo8", "kannada"),
  cbgSong("Upavasa", "Sonu Nigam, Shreya Ghoshal", "Mr. and Mrs. Ramachari", "2014", "10s", ["romantic","sukoon","shaam"], "iPOCZdhEf28", "kannada"),
  cbgSong("Matthe Maleyagide", "Sonu Nigam, Shreya Ghoshal", "Chakravarthy", "2017", "10s", ["baarish","romantic","sukoon","shaam"], "gB4ErkONc2w", "kannada"),
  cbgSong("Saaluthillave", "Vijay Prakash, Shreya Ghoshal", "Kotigobba 2", "2016", "10s", ["romantic","sukoon","shaam"], "8iCcyOekVpc", "kannada"),
  cbgSong("Neenire Saniha", "Shreya Ghoshal", "Kirik Party", "2016", "10s", ["romantic","sukoon","shaam"], "wkay45hn-Vs", "kannada"),
  cbgSong("Nodivalandava", "Armaan Malik, Shreya Ghoshal", "The Villain", "2018", "10s", ["romantic","sukoon"], "Z6-SBQeez_w", "kannada"),
  cbgSong("Anisuthidhe", "Shreya Ghoshal", "99", "2019", "10s", ["sad","nostalgic","sukoon","shaam"], "BzEY_tWKxx0", "kannada"),
  cbgSong("Summane Heege Ninnane", "Sonu Nigam, Shreya Ghoshal", "Amar", "2019", "10s", ["romantic","sukoon","safar","shaam"], "MRmhCQS9fIs", "kannada"),
  cbgSong("Naa Sanihake Innu", "Shreya Ghoshal", "99", "2019", "10s", ["nostalgic","sad","sukoon","shaam"], "QoKbr4MhlJo", "kannada"),
  cbgSong("Hrudayave Bayaside Ninnane", "Sonu Nigam", "Krishnan Love Story", "2010", "10s", ["romantic","sukoon","shaam","sad"], "pPfKDjKSl-s", "kannada"),
  cbgSong("Kanna Minche", "Sonu Nigam", "Victory", "2013", "10s", ["romantic","sukoon"], "gtb5KtRJASs", "kannada"),
  cbgSong("Yenammi Yenammi", "Vijay Prakash, Palak Muchhal", "Ayogya", "2018", "10s", ["romantic","sukoon","shaam"], "chLTOMbgLO0", "kannada"),
  cbgSong("Ninthe Ninthe", "Vijay Prakash, Chinmayi", "Ninnindale", "2014", "10s", ["romantic","sukoon","safar"], "TwOzSAFqvbg", "kannada"),
  cbgSong("Gatiya Ilidu", "Vijay Prakash, B. Ajaneesh Loknath", "Ulidavaru Kandanthe", "2014", "10s", ["nostalgic","shaam","sukoon"], "1VwZ1tnDZbs", "kannada"),
  cbgSong("Khali Quarter Batli", "Vijay Prakash", "Victory", "2013", "10s", ["nostalgic"], "N0zkVn8tVoU", "kannada"),
  cbgSong("Shaane Top Agavle", "Vijay Prakash", "Singa", "2019", "10s", ["romantic"], "zrT0rMSQyeM", "kannada"),
  cbgSong("Yavva Yavva", "Vijay Prakash", "Raambo 2", "2018", "10s", ["romantic","safar"], "pDsr6DJwFRw", "kannada"),
  cbgSong("Heege Doora", "Vijay Prakash", "99", "2019", "10s", ["sad","nostalgic","sukoon","shaam"], "BqF24x1Zry0", "kannada"),
  cbgSong("Ammi Ammi", "Vijay Prakash", "Preethiya Raayabhari", "2018", "10s", ["romantic","sukoon"], "VH3sJv4SCVk", "kannada"),
  cbgSong("Early Morning", "Vijay Prakash", "Dalapathi", "2018", "10s", ["romantic","sukoon"], "vHe-aTXqvO4", "kannada"),

  /* Kannada 2020s */
  cbgSong("Dwapara", "Jaskaran Singh", "Krishnam Pranaya Sakhi", "2024", "20s", ["romantic","sukoon"], "C93Tcb9wJRE", "kannada"),
  cbgSong("Sapta Sagaradaache Ello Title Track", "Kapil Kapilan", "Sapta Sagaradaache Ello - Side A", "2023", "20s", ["baarish","romantic","sukoon","shaam","sad"], "dDMXyQ6cwIc", "kannada"),
  cbgSong("Kadalanu Kaana Horatiro", "Charan Raj, Srilakshmi Belmannu", "Sapta Sagaradaache Ello - Side A", "2023", "20s", ["sukoon","shaam","safar","nostalgic"], "i_vRoQGIc6Y", "kannada"),
  cbgSong("Kannu Hodiyaka", "Shreya Ghoshal", "Roberrt", "2021", "20s", ["romantic"], "PyrbIANon98", "kannada"),
  cbgSong("Nannavale Nannavale", "Sonu Nigam", "Inspector Vikram", "2021", "20s", ["romantic","sukoon"], "dkZS8dIiZ-M", "kannada"),
  cbgSong("Bombe Bombe", "Sonu Nigam", "Kranti", "2023", "20s", ["sukoon","nostalgic"], "b5ttA1-VaiE", "kannada"),
  cbgSong("Singara Siriye", "Vijay Prakash, Ananya Bhat", "Kantara", "2022", "20s", ["romantic","baarish","sukoon","safar"], "3XShkcOze3s", "kannada"),
  cbgSong("Pataki Poriyo", "Vijay Prakash, Anuradha Bhat", "Kotigobba 3", "2021", "20s", ["romantic"], "J4zjLb2MhoU", "kannada"),
  cbgSong("Devle Devle", "Vijay Prakash", "Gaalipata 2", "2022", "20s", ["nostalgic","safar"], "dhCIo7lEnsQ", "kannada"),
  cbgSong("Aane Maadi Heluteeni", "Vijay Prakash, Nihal Tauro", "Guru Shishyaru", "2022", "20s", ["romantic","sukoon"], "gNxQAa8NpQg", "kannada"),
  cbgSong("Udupi Hotelu", "Vijay Prakash", "Badava Rascal", "2021", "20s", ["nostalgic","safar"], "fmOUogcvFS4", "kannada"),

  /* Malayalam — verified runtime catalog */
  cbgSong("Thamasamenthe Varuvan", "K. J. Yesudas", "Bhargavi Nilayam", "1964", "60s", ["old-gold","romantic","sukoon"], "g7aDaOBvzEw", "malayalam"),
  cbgSong("Anuraga Ganam Pole", "P. Jayachandran", "Udyogastha", "1967", "60s", ["old-gold","romantic","sukoon"], "Em3wmM8knO0", "malayalam"),
  cbgSong("Sanyasini", "K. J. Yesudas", "Rajahamsam", "1974", "70s", ["old-gold","sad","sukoon"], "F2_po_3NYWw", "malayalam"),
  cbgSong("Manushyan Mathangale Srishtichu", "K. J. Yesudas", "Achanum Bappayum", "1972", "70s", ["old-gold","nostalgic","sukoon"], "leikh4I9MZY", "malayalam"),
  cbgSong("Thumbi Vaa", "S. Janaki", "Olangal", "1982", "80s", ["old-gold","sukoon","nostalgic"], "bLbuaKQpy1M", "malayalam"),
  cbgSong("Thenum Vayambum", "K. J. Yesudas", "Thenum Vayambum", "1981", "80s", ["old-gold","romantic","sukoon"], "P456eneF6jg", "malayalam"),
  cbgSong("Vaishakha Sandhye", "K. J. Yesudas", "Nadodikkattu", "1987", "80s", ["old-gold","romantic","shaam"], "xN2eev1LWh0", "malayalam"),
  cbgSong("Pramadavanam", "K. J. Yesudas", "His Highness Abdullah", "1990", "90s", ["old-gold","sukoon","shaam"], "ZRdHUj7gVSc", "malayalam"),
  cbgSong("Devasabhathalam", "K. J. Yesudas, Raveendran, Sharreth", "His Highness Abdullah", "1990", "90s", ["old-gold","sukoon"], "soyx2Ynuaz8", "malayalam"),
  cbgSong("Gopika Vasantham", "K. J. Yesudas", "His Highness Abdullah", "1990", "90s", ["old-gold","romantic","sukoon"], "KE0YE530BLs", "malayalam"),
  cbgSong("Sreeragamo", "K. J. Yesudas", "Pavithram", "1994", "90s", ["old-gold","sukoon","shaam"], "t35SFA3kWy4", "malayalam"),
  cbgSong("Varamanjal", "Sujatha Mohan", "Pranayavarnangal", "1998", "90s", ["romantic","sukoon","nostalgic"], "BKbWMHLff3Y", "malayalam"),
  cbgSong("Kannadi Koodum Kootti", "K. J. Yesudas, K. S. Chithra", "Pranayavarnangal", "1998", "90s", ["romantic","nostalgic","sukoon"], "YC3ujn41g-I", "malayalam"),
  cbgSong("Aaro Viral Neetti", "K. J. Yesudas", "Pranayavarnangal", "1998", "90s", ["romantic","sad","sukoon"], "riI3FqDM_0g", "malayalam"),
  cbgSong("Othiri Othiri Swapnangal", "K. S. Chithra", "Pranayavarnangal", "1998", "90s", ["romantic","nostalgic","sukoon"], "uwZEpHYtFKA", "malayalam"),
  cbgSong("Ethrayo Janmamayi", "Sreenivas, Sujatha Mohan", "Summer in Bethlehem", "1998", "90s", ["romantic","nostalgic","sukoon"], "SbxAua09qo4", "malayalam"),
  cbgSong("Vennila Chandana Kinnam", "K. J. Yesudas, Shabnam", "Azhakiya Ravanan", "1996", "90s", ["romantic","sukoon","shaam"], "UUHUWxoSPGw", "malayalam"),

  cbgSong("Ariyathe Ariyathe", "P. Jayachandran, K. S. Chithra", "Ravanaprabhu", "2001", "00s", ["romantic","sukoon","nostalgic"], "1WgeGByWSXM", "malayalam"),
  cbgSong("Karimizhi Kuruviye", "V. Devanand, Sujatha Mohan", "Meesa Madhavan", "2002", "00s", ["romantic","sukoon"], "hraTNj9Au-A", "malayalam"),
  cbgSong("Ente Ellam Ellam Alle", "K. J. Yesudas, Sujatha Mohan", "Meesa Madhavan", "2002", "00s", ["romantic","sukoon"], "sZvDWK8bjt8", "malayalam"),
  cbgSong("Chingamasam Vannu Chernnal", "Shankar Mahadevan, Rimi Tomy", "Meesa Madhavan", "2002", "00s", ["nostalgic","safar"], "IL5byzq70ls", "malayalam"),
  cbgSong("Lajjavathiye", "Jassie Gift", "4 the People", "2004", "00s", ["nostalgic","safar"], "Tfi3oWgZp1Y", "malayalam"),
  cbgSong("Kaanumbol Parayaamo", "K. J. Yesudas, K. S. Chithra", "Ishtam", "2001", "00s", ["romantic","sukoon"], "LhHPSusaugs", "malayalam"),
  cbgSong("Manju Pole", "Sreenivas", "Dosth", "2001", "00s", ["romantic","sukoon","shaam"], "56Gw6kMD-V8", "malayalam"),
  cbgSong("Sukhamaanee Nilavu", "Vidhu Prathap, Jyotsna Radhakrishnan", "Nammal", "2002", "00s", ["romantic","sukoon","shaam"], "4vSAy_cHiJg", "malayalam"),
  cbgSong("Ente Khalbile", "Vineeth Sreenivasan", "Classmates", "2006", "00s", ["romantic","nostalgic","sukoon"], "I2-JBtOZ8H0", "malayalam"),
  cbgSong("Mazhathullikal", "M. G. Sreekumar", "Vettam", "2004", "00s", ["baarish","romantic","sukoon"], "S-MY1mf_1pc", "malayalam"),
  cbgSong("Pachappanamthathe", "K. J. Yesudas", "Nottam", "2006", "00s", ["sukoon","nostalgic"], "kzJ9wh3PHw0", "malayalam"),
  cbgSong("Karuppinazhaku", "Rajesh Vijay, Jyotsna Radhakrishnan", "Swapnakoodu", "2003", "00s", ["romantic","nostalgic"], "Pg5SWsBgKnk", "malayalam"),
  cbgSong("Marannittum Enthino", "P. Jayachandran, Sujatha Mohan", "Randam Bhavam", "2001", "00s", ["sad","nostalgic","sukoon"], "Oh-4ilpj3vg", "malayalam"),
  cbgSong("Shilayil Ninnum", "Sujatha Mohan", "Chronic Bachelor", "2003", "00s", ["romantic","sukoon"], "GCsXxqc3PSM", "malayalam"),
  cbgSong("Pranaya Sowgandhikangal", "Santhosh Keshav", "Darling Darling", "2000", "00s", ["romantic","sukoon"], "yVtzCzzcxuo", "malayalam"),
  cbgSong("Dwaadashiyil", "K. J. Yesudas, Sujatha Mohan", "Madhuranombarakattu", "2000", "00s", ["romantic","sukoon","shaam"], "Abj8wQEGisY", "malayalam"),
  cbgSong("Aattinkarayorathe", "Manjari", "Rasathanthram", "2006", "00s", ["nostalgic","sukoon"], "_MkXI4cUNZ8", "malayalam"),
  cbgSong("Thotturummi Irikkan", "V. Devanand, Sujatha Mohan", "Rasikan", "2004", "00s", ["romantic","sukoon"], "pjZEsPVfsKI", "malayalam"),
  cbgSong("Kasavinte Thattamittu", "Vineeth Sreenivasan, Sujatha Mohan", "Kilichundan Mampazham", "2003", "00s", ["romantic","nostalgic"], "Qzx6TxAcloI", "malayalam"),
  cbgSong("Manassil Mithunamazha", "M. G. Sreekumar", "Nandanam", "2002", "00s", ["baarish","romantic","sukoon"], "2B1bNfVZPac", "malayalam"),

  cbgSong("Muthuchippi Poloru", "Sachin Warrier, Ramya Nambeesan", "Thattathin Marayathu", "2012", "10s", ["romantic","sukoon"], "Xq2GDrTNTXE", "malayalam"),
  cbgSong("Shyamambaram", "Vineeth Sreenivasan", "Thattathin Marayathu", "2012", "10s", ["romantic","sukoon","shaam"], "9ACmSKu3EU8", "malayalam"),
  cbgSong("Appangal Embadum", "Gopi Sundar, Anna Katharina Valayil", "Ustad Hotel", "2012", "10s", ["nostalgic","safar"], "QcESg-9Vfzo", "malayalam"),
  cbgSong("Vathilil", "Haricharan", "Ustad Hotel", "2012", "10s", ["romantic","sukoon"], "AtytJtQum5Q", "malayalam"),
  cbgSong("Malare", "Vijay Yesudas", "Premam", "2015", "10s", ["romantic","sukoon","shaam"], "0G2VxhV_gXM", "malayalam"),
  cbgSong("Aluva Puzha", "Vineeth Sreenivasan", "Premam", "2015", "10s", ["romantic","nostalgic","safar"], "fiAlruU48HI", "malayalam"),
  cbgSong("Pathivaayi Njan", "Shabareesh Varma, Rajesh Murugesan", "Premam", "2015", "10s", ["nostalgic","safar"], "1DF1nOfUIaU", "malayalam"),
  cbgSong("Aethu Kari Raavilum", "Haricharan", "Bangalore Days", "2014", "10s", ["romantic","sukoon","shaam"], "LjG7E8Mg7UM", "malayalam"),
  cbgSong("Maangalyam", "Vijay Yesudas, Sachin Warrier, Divya S. Menon", "Bangalore Days", "2014", "10s", ["nostalgic","safar"], "WS4Mev_vRAc", "malayalam"),
  cbgSong("Thumbi Penne", "Siddharth Menon", "Bangalore Days", "2014", "10s", ["romantic","sukoon","safar"], "FVjaEaK4kmc", "malayalam"),
  cbgSong("Ente Kannil Ninakkai", "Gopi Sundar, Nazriya Nazim", "Bangalore Days", "2014", "10s", ["romantic","sukoon","shaam"], "3UwVodF5Yu8", "malayalam"),
  cbgSong("Mukkathe Penne", "Mohammed Maqbool Mansoor, Gopi Sundar", "Ennu Ninte Moideen", "2015", "10s", ["romantic","sad","sukoon"], "graP-a1MxN4", "malayalam"),
  cbgSong("Kaathirunnu", "Shreya Ghoshal", "Ennu Ninte Moideen", "2015", "10s", ["romantic","sad","sukoon"], "qycMVIrlO5s", "malayalam"),
  cbgSong("Kannondu Chollanu", "Shreya Ghoshal, Vijay Yesudas", "Ennu Ninte Moideen", "2015", "10s", ["romantic","sukoon"], "kQ5F1Bc4DtQ", "malayalam"),
  cbgSong("Chundari Penne", "Dulquer Salmaan", "Charlie", "2015", "10s", ["romantic","safar","sukoon"], "P8b6eoMu_Vo", "malayalam"),
  cbgSong("Vaarthinkale", "Divya S. Menon", "Kali", "2016", "10s", ["romantic","sukoon","shaam"], "rykWOFTvMpQ", "malayalam"),
  cbgSong("Ee Kaattu", "Karthik", "Adam Joan", "2017", "10s", ["romantic","safar","shaam"], "TFwZuS8Kkcc", "malayalam"),
  cbgSong("Lailakame", "Haricharan", "Ezra", "2017", "10s", ["romantic","sukoon","shaam"], "FAn2i7gu32w", "malayalam"),
  cbgSong("Entammede Jimikki Kammal", "Vineeth Sreenivasan, Renjith Unni", "Velipadinte Pusthakam", "2017", "10s", ["nostalgic","safar"], "FXiaIH49oAU", "malayalam"),
  cbgSong("Aaro Nenjil", "Gowry Lekshmi", "Godha", "2017", "10s", ["romantic","sukoon"], "603EgjJjeRk", "malayalam"),
  cbgSong("Mizhiyil Ninnum", "Shahabaz Aman", "Mayaanadhi", "2017", "10s", ["romantic","sad","sukoon"], "VRj3ROIpEEc", "malayalam"),
  cbgSong("Uyirin Nadhiye", "Rex Vijayan, Neha S. Nair", "Mayaanadhi", "2017", "10s", ["romantic","sukoon","shaam"], "jK4KtJXfWEM", "malayalam"),
  cbgSong("Jeevamshamayi", "K. S. Harisankar, Shreya Ghoshal", "Theevandi", "2018", "10s", ["romantic","sukoon","shaam"], "Rx_xAjRFJMw", "malayalam"),
  cbgSong("Pavizha Mazha", "K. S. Harisankar", "Athiran", "2019", "10s", ["baarish","romantic","sukoon"], "ZCiDEc-QE5s", "malayalam"),
  cbgSong("Uyiril Thodum", "Sooraj Santhosh, Anne Amie", "Kumbalangi Nights", "2019", "10s", ["romantic","sukoon","shaam"], "d59JbNRFkuI", "malayalam"),
  cbgSong("Cherathukal", "Sushin Shyam, Sithara Krishnakumar", "Kumbalangi Nights", "2019", "10s", ["sukoon","shaam","nostalgic"], "uA5aBB0FOEI", "malayalam"),
  cbgSong("Parayuvaan", "Sid Sriram, Neha Nair", "Ishq", "2019", "10s", ["romantic","sukoon"], "IWOPRFRNj3g", "malayalam"),

  cbgSong("Vathikkalu Vellaripravu", "Arjun Krishna, Nithya Mammen, Zia Ul Haq", "Sufiyum Sujatayum", "2020", "20s", ["romantic","sukoon"], "H1UdC4ejBFs", "malayalam"),
  cbgSong("Kalakkatha Sandana Meram", "Nanjiyamma", "Ayyappanum Koshiyum", "2020", "20s", ["old-gold","nostalgic","safar"], "mR2wpadUDUA", "malayalam"),
  cbgSong("Aakashamayavale", "Shahabaz Aman", "Vellam", "2021", "20s", ["sukoon","sad","shaam"], "Ri_0ow-JOFY", "malayalam"),
  cbgSong("Uyire", "Narayani Gopan, Mithun Jayaraj", "Minnal Murali", "2021", "20s", ["romantic","sukoon"], "Fd7-FybJlbs", "malayalam"),
  cbgSong("Theerame", "K. S. Chithra, Sooraj Santhosh", "Malik", "2021", "20s", ["romantic","sad","sukoon"], "18cpx0zI6SY", "malayalam"),
  cbgSong("Parudeesa", "Sreenath Bhasi", "Bheeshma Parvam", "2022", "20s", ["safar","shaam"], "O_ZIs4p14Fo", "malayalam"),
  cbgSong("Neela Nilave", "Kapil Kapilan", "RDX", "2023", "20s", ["romantic","sukoon","shaam"], "5BMvVvk2aGA", "malayalam"),
  /* Telugu — verified runtime catalog */
  cbgSong("Thakita Thadimi", "S. P. Balasubrahmanyam", "Sagara Sangamam", "1983", "80s", ["old-gold","sukoon","nostalgic"], "EnGYS9DesTk", "telugu"),
  cbgSong("Chukkallo Chandrude", "S. P. Balasubrahmanyam, S. Janaki", "Aakhari Poratam", "1988", "80s", ["romantic","nostalgic"], "NAumVu6fdDM", "telugu"),
  cbgSong("Botany Paatamundi", "S. P. Balasubrahmanyam, S. Janaki", "Shiva", "1989", "80s", ["nostalgic","safar"], "0vh8_1ruoRo", "telugu"),
  cbgSong("Bangaru Kodi Petta", "S. P. Balasubrahmanyam, K. S. Chithra", "Gharana Mogudu", "1992", "90s", ["nostalgic","safar"], "hxvUiz6s4Gk", "telugu"),
  cbgSong("Yamaha Nagari", "Hariharan", "Choodalani Vundi", "1998", "90s", ["nostalgic","safar","sukoon"], "xASv7AFvSuc", "telugu"),
  cbgSong("Cheppave Prema", "Usha, K. S. Chithra", "Manasantha Nuvve", "2001", "00s", ["romantic","sad","sukoon"], "W50msiw0Keg", "telugu"),
  cbgSong("Cheliya Cheliya", "KK, Suchitra", "Gharshana", "2004", "00s", ["romantic","sukoon","shaam"], "RLDGpFUWAkc", "telugu"),
  cbgSong("Nee Kosam", "Rajesh, Shreya Ghoshal", "Nenunnanu", "2004", "00s", ["romantic","sukoon","shaam"], "dYgWt9GkVl4", "telugu"),
  cbgSong("Kopama Naa Paina", "Karthik, Shreya Ghoshal", "Varsham", "2004", "00s", ["romantic","baarish","sukoon"], "Mlubxn-J_0o", "telugu"),
  cbgSong("Yamunatheeram", "Hariharan, K. S. Chithra", "Anand", "2004", "00s", ["romantic","sukoon"], "pgsaLjEiPy4", "telugu"),
  cbgSong("Nuvvostanante Nenoddantana", "K. S. Chithra, Raqeeb Alam", "Nuvvostanante Nenoddantana", "2005", "00s", ["romantic","sukoon","baarish"], "TTGQX0CXlL0", "telugu"),
  cbgSong("Muvvala Navakala", "K. S. Chithra, S. P. Balasubrahmanyam", "Pournami", "2006", "00s", ["romantic","sukoon","baarish"], "WlfLkcod13Y", "telugu"),
  cbgSong("Chalore Chalore", "Devan Ekambaram", "Jalsa", "2008", "00s", ["safar","nostalgic"], "cQpe2HMkqVA", "telugu"),
  cbgSong("Nenu Nuvvantu", "Naresh Iyer, Nadeem Mudda", "Orange", "2010", "10s", ["romantic","sukoon"], "Kre9YbJ-DiU", "telugu"),
  cbgSong("O Madhu", "Adnan Sami", "Julayi", "2012", "10s", ["romantic","sukoon","shaam"], "fKCl0XfMZzM", "telugu"),
  cbgSong("Gusa Gusa Lade", "Karthik, Suchitra", "Damarukam", "2012", "10s", ["romantic","sukoon","shaam"], "EO3JWdSL1mk", "telugu"),
  cbgSong("Bapu Gari Bomma", "Shankar Mahadevan", "Attarintiki Daredi", "2013", "10s", ["romantic","sukoon","shaam"], "QObvsMnwthI", "telugu"),
  cbgSong("Inka Cheppale", "Rahul Nambiar, Anjana Sowmya", "Seethamma Vakitlo Sirimalle Chettu", "2013", "10s", ["romantic","sukoon"], "5J-8vmMVKjs", "telugu"),
  cbgSong("Chinni Chinni Aasalu", "Ashwin, Hari", "Manam", "2014", "10s", ["romantic","sukoon"], "XBYuSGk7CsY", "telugu"),
  cbgSong("Mental Madhilo", "Krishna Chaitanya, Shashaa Tirupati", "OK Bangaram", "2015", "10s", ["romantic","sukoon","shaam"], "jEuojck5M7U", "telugu"),
  cbgSong("Chinuku Taake", "Amritavarshini KC", "Pelli Choopulu", "2016", "10s", ["romantic","baarish","sukoon"], "LGQ-hkDfMaI", "telugu"),
  cbgSong("Telisiney Na Nuvvey", "Revanth", "Arjun Reddy", "2017", "10s", ["sad","romantic","sukoon"], "jOst7Trpj7o", "telugu"),
  cbgSong("Hey Pillagada", "Sindhuri, Shakthikanth Karthick", "Fidaa", "2017", "10s", ["romantic","sukoon","shaam"], "k9DMXBFHEH4", "telugu"),
  cbgSong("Oosupodu", "Hemachandra", "Fidaa", "2017", "10s", ["romantic","sukoon","shaam"], "5L4ZLPKSVlY", "telugu"),
  cbgSong("Adiga Adiga", "Sid Sriram", "Ninnu Kori", "2017", "10s", ["romantic","sad","sukoon"], "hJ4OL9NNeDY", "telugu"),
  cbgSong("Inkem Inkem Inkem Kaavaale", "Sid Sriram", "Geetha Govindam", "2018", "10s", ["romantic","sukoon","shaam"], "iOgjIr9dpS4", "telugu"),
  cbgSong("Rangamma Mangamma", "M. M. Manasi", "Rangasthalam", "2018", "10s", ["nostalgic","safar"], "GWWHI7SE0KQ", "telugu"),
  cbgSong("Mooga Manasulu", "Anurag Kulkarni, Shreya Ghoshal", "Mahanati", "2018", "10s", ["romantic","nostalgic","sukoon"], "7weHJNesf2I", "telugu"),
  cbgSong("Undiporaadhey", "Sid Sriram", "Hushaaru", "2018", "10s", ["romantic","sukoon","shaam"], "wCnUAKzAmVo", "telugu"),
  cbgSong("Mellaga Mellaga", "Chinmayi Sripada", "Chi La Sow", "2018", "10s", ["romantic","sukoon","shaam"], "A-YrNi_ZZQY", "telugu"),
  cbgSong("Adhento Gaani Vunnapaatuga", "Anirudh Ravichander", "Jersey", "2019", "10s", ["romantic","sukoon","safar"], "U7uYYwHOcmA", "telugu"),
  cbgSong("Chalaname Chitramu", "Shashaa Tirupati", "Brochevarevarura", "2019", "10s", ["romantic","sukoon"], "FldLc4ulKsA", "telugu"),
  cbgSong("Vagalaadi", "Vivek Sagar, Balaji Dake, Ram Miriyala, Manisha Erabathini", "Brochevarevarura", "2019", "10s", ["nostalgic","safar"], "u9zL_hxdbWk", "telugu"),
  cbgSong("Samajavaragamana", "Sid Sriram", "Ala Vaikunthapurramuloo", "2020", "20s", ["romantic","sukoon","shaam"], "Thf60JU8E98", "telugu"),
  cbgSong("Butta Bomma", "Armaan Malik", "Ala Vaikunthapurramuloo", "2020", "20s", ["romantic","safar","sukoon"], "6DR5HU6kcbU", "telugu"),
  cbgSong("Sara Sari", "Anurag Kulkarni", "Bheeshma", "2020", "20s", ["romantic","sukoon","shaam"], "pycfc5GD7Hw", "telugu"),
  cbgSong("Manasu Maree", "Amit Trivedi, Shashaa Tirupati, Yazin Nizar", "V", "2020", "20s", ["romantic","sukoon","shaam"], "FxyFrOud3Yk", "telugu"),
  cbgSong("Srivalli", "Sid Sriram", "Pushpa: The Rise", "2021", "20s", ["romantic","sukoon","safar"], "hcMzwMrr1tE", "telugu"),
  cbgSong("Saami Saami", "Mounika Yadav", "Pushpa: The Rise", "2021", "20s", ["nostalgic","safar"], "C70GJYVoZ4Y", "telugu"),
  cbgSong("Oo Antava Oo Oo Antava", "Indravathi Chauhan", "Pushpa: The Rise", "2021", "20s", ["nostalgic","safar"], "u_wB6byrl5k", "telugu"),
  cbgSong("Nee Kannu Neeli Samudram", "Javed Ali, Srikanth Chandra", "Uppena", "2021", "20s", ["romantic","sukoon","shaam"], "ZiNhfv0F4DY", "telugu"),
  cbgSong("Jala Jala Jalapaatham", "Jaspreet Jasz, Shreya Ghoshal", "Uppena", "2021", "20s", ["romantic","baarish","sukoon"], "PTpimuHzlvE", "telugu"),
  cbgSong("Saranga Dariya", "Mangli", "Love Story", "2021", "20s", ["baarish","nostalgic"], "1ozmyl1ZEyY", "telugu"),
  cbgSong("Ay Pilla", "Haricharan", "Love Story", "2021", "20s", ["romantic","sukoon","shaam"], "KRmbTCvJ6ns", "telugu"),
  cbgSong("Evo Evo Kalale", "Jonita Gandhi, Anurag Kulkarni", "Love Story", "2021", "20s", ["baarish","romantic","sukoon"], "05HYHpDKR2k", "telugu"),
  cbgSong("Inthandham", "S. P. Charan", "Sita Ramam", "2022", "20s", ["romantic","sukoon","shaam"], "VHDKxkiyai8", "telugu"),
  cbgSong("Oh Sita Hey Rama", "S. P. Charan, Ramya Behara", "Sita Ramam", "2022", "20s", ["romantic","sukoon","shaam"], "POmbwLdiGCQ", "telugu"),
  cbgSong("Kalaavathi", "Sid Sriram", "Sarkaru Vaari Paata", "2022", "20s", ["romantic","sukoon","shaam"], "Vbu44JdN12s", "telugu"),
  cbgSong("Gundellonaa", "Anirudh Ravichander", "Ori Devuda", "2022", "20s", ["romantic","safar","sukoon"], "YExx3N8xa_E", "telugu"),
  cbgSong("Entha Chithram", "Anurag Kulkarni, Keerthana Vaidyanathan", "Ante Sundaraniki", "2022", "20s", ["romantic","sukoon","shaam"], "pOmPTwA3fsU", "telugu"),
  cbgSong("Nagumomu Thaarale", "Sid Sriram", "Radhe Shyam", "2022", "20s", ["romantic","sukoon","shaam"], "6yarf3r9Hak", "telugu"),
  cbgSong("Ee Raathale", "Yuvan Shankar Raja, Haricharan", "Radhe Shyam", "2022", "20s", ["romantic","sukoon","safar"], "vHuBCcm7KC8", "telugu"),
  cbgSong("Halamithi Habibo", "Anirudh Ravichander, Jonita Gandhi", "Beast", "2022", "20s", ["romantic","safar"], "vOYJmUE_U24", "telugu"),
  cbgSong("Gaaju Bomma", "Hesham Abdul Wahab", "Hi Nanna", "2023", "20s", ["sukoon","nostalgic","sad"], "zNFlJqvxwdg", "telugu"),
  cbgSong("Ammaadi", "Kaala Bhairava, Shakthisree Gopalan", "Hi Nanna", "2023", "20s", ["romantic","sukoon","shaam"], "uQyUcknlZq0", "telugu"),
  cbgSong("Samayama", "Anurag Kulkarni, Sithara Krishnakumar", "Hi Nanna", "2023", "20s", ["romantic","sukoon","shaam"], "8I9v8yaaknM", "telugu"),
  cbgSong("Aradhya", "Sid Sriram, Chinmayi", "Kushi", "2023", "20s", ["romantic","sukoon","shaam"], "0OEZgrd9reM", "telugu"),
  cbgSong("Nanna Nuv Naa Pranam", "Sonu Nigam", "Animal", "2023", "20s", ["sad","sukoon","nostalgic"], "0u3B2LZJgMc", "telugu"),
  cbgSong("Evarevaro", "Vishal Mishra", "Animal", "2023", "20s", ["sad","sukoon"], "Xbizke4zftY", "telugu"),
  cbgSong("Chilipiga", "Karthik", "Orange", "2010", "10s", ["romantic","sukoon"], "qkwr0t_z3jU", "telugu"),
  cbgSong("Badass", "Anirudh Ravichander, Sri Krishna", "Leo", "2023", "20s", ["safar","nostalgic"], "IcYKpiVppDc", "telugu"),
  cbgSong("Hukum", "Anirudh Ravichander", "Jailer", "2023", "20s", ["safar","nostalgic"], "fgZ9pJbVA3c", "telugu"),
  cbgSong("Kurchi Madathapetti", "Sahithi Chaganti, Sri Krishna", "Guntur Kaaram", "2024", "20s", ["safar","nostalgic"], "qSc_sjKBdX0", "telugu"),
  cbgSong("Chuttamalle", "Shilpa Rao", "Devara: Part 1", "2024", "20s", ["romantic","sukoon","shaam"], "5vsOv_bcnhs", "telugu"),
  cbgSong("Poolamme Pilla", "GowraHari", "Hanu-Man", "2024", "20s", ["romantic","sukoon","nostalgic"], "CS7hBHVGWs0", "telugu"),
  cbgSong("Theme of Kalki", "Kaala Bhairava, Gowtham Bharadwaj", "Kalki 2898 AD", "2024", "20s", ["sukoon","nostalgic"], "RZysj-443-8", "telugu"),
  cbgSong("Sooseki", "Shreya Ghoshal", "Pushpa 2: The Rule", "2024", "20s", ["romantic","sukoon","shaam"], "LH6c2bTM8p0", "telugu"),
  cbgSong("Aho Balu", "Ranjith", "100% Love", "2011", "10s", ["romantic","safar"], "494LFBXC8b4", "telugu"),
  cbgSong("Ammaadi", "Ram Miriyala", "Aay", "2024", "20s", ["romantic","sukoon","shaam"], "pFUI4P17LIE", "telugu"),
  cbgSong("Ranganayaki", "Anurag Kulkarni", "Aay", "2024", "20s", ["romantic","safar"], "7aKg4EaYfQk", "telugu"),
  cbgSong("Godari Gattu Meedha", "Ramana Gogula, Madhupriya", "Sankranthiki Vasthunnam", "2025", "20s", ["nostalgic","safar"], "L8s6qxQJKgk", "telugu"),
];
