/*
 * CHAI BAARISH GAANE — playlist.js
 *
 * Runtime track schema:
 *   title, artist, film, year, decade, language, moods, youtubeId
 *
 * A blank youtubeId means that the song is intentionally awaiting the next
 * dedicated YouTube verification pass. IDs are never inferred here.
 */
const cbgSong = (title, artist, film, year, decade, moods = ["romantic"], youtubeId = "", language = "hindi") => ({
  title,
  artist,
  film,
  year,
  decade,
  language,
  moods,
  youtubeId
});

window.CBG_PLAYLIST = [
  /* Evergreen / Older */
  cbgSong("Rimjhim Gire Saawan", "Kishore Kumar", "Manzil", "1979", "70s", ["baarish","romantic","sukoon"], "JQoSSJDZxOo"),
  cbgSong("Bheegi Bheegi Raaton Mein", "Kishore Kumar, Lata Mangeshkar", "Ajanabee", "1974", "70s", ["baarish","romantic","old-gold"], "NkgLsX1Yeec"),
  cbgSong("Pal Pal Dil Ke Paas", "Kishore Kumar", "Blackmail", "1973", "70s", ["romantic","nostalgic"], "AMuRRXCuy-4"),
  cbgSong("Aap Ki Aankhon Mein Kuch", "Kishore Kumar, Lata Mangeshkar", "Ghar", "1978", "70s", ["romantic","sukoon","old-gold"], "daxuKHBWiKE"),
  cbgSong("Neele Neele Ambar Par", "Kishore Kumar", "Kalaakaar", "1983", "80s", ["romantic","shaam","sukoon"], "ThHYiiZTB1Y"),
  cbgSong("Humein Tumse Pyaar Kitna", "Kishore Kumar", "Kudrat", "1981", "80s", ["romantic","sad"], "iTkTrVXwCsA"),
  cbgSong("Kya Mujhe Pyar Hai", "KK", "Woh Lamhe", "2006", "00s", ["romantic","sad"], "Gg6NMU4ivXM"),
  cbgSong("Lag Ja Gale", "Lata Mangeshkar", "Woh Kaun Thi?", "1964", "60s", ["romantic","sad","sukoon"], "br6C4U3Dyfo"),
  cbgSong("Gulabi Aankhen", "Mohammed Rafi", "The Train", "1970", "70s", ["romantic","old-gold"], "KWAdrB2U7cE"),
  cbgSong("Chura Liya Hai Tumne", "Asha Bhosle, Mohammed Rafi", "Yaadon Ki Baaraat", "1973", "70s", ["romantic","old-gold"], "KT0NlItK86A"),
  cbgSong("Pehla Nasha", "Udit Narayan, Sadhana Sargam", "Jo Jeeta Wohi Sikandar", "1992", "90s", ["romantic","nostalgic"], "SBfPs-PMGTA"),
  cbgSong("Ek Ladki Ko Dekha", "Kumar Sanu", "1942: A Love Story", "1994", "90s", ["romantic","nostalgic"], "fTauOK8J-U8"),
  cbgSong("Do Dil Mil Rahe Hain", "Kumar Sanu", "Pardes", "1997", "90s", ["romantic","nostalgic"], "dReDtHKF0-g"),
  cbgSong("Aankhon Mein Base Ho Tum", "Abhijeet, Alka Yagnik", "Takkar", "1995", "90s", ["romantic","nostalgic"], "S1st8FCEgkY"),
  cbgSong("Mera Dil Bhi Kitna Pagal Hai", "Kumar Sanu, Alka Yagnik", "Saajan", "1991", "90s", ["romantic","sad"], "RVQsBlI35vw"),
  cbgSong("Dheere Dheere Se Meri Zindagi Mein Aana", "Kumar Sanu, Anuradha Paudwal", "Aashiqui", "1990", "90s", ["romantic","nostalgic"], "KeyfUuXPOcY"),
  cbgSong("Tujhe Dekha To", "Kumar Sanu, Lata Mangeshkar", "Dilwale Dulhania Le Jayenge", "1995", "90s", ["romantic","safar"], "cNV5hLSa9H8"),
  cbgSong("Aaye Ho Meri Zindagi Mein", "Udit Narayan", "Raja Hindustani", "1996", "90s", ["romantic","nostalgic"], "Mj3KyjuKbqI"),
  cbgSong("Tere Dar Par Sanam", "Kumar Sanu", "Phir Teri Kahani Yaad Aayee", "1993", "90s", ["romantic","sad"], "05o4kCUY2Ys"),
  cbgSong("Bahut Pyar Karte Hain", "Anuradha Paudwal", "Saajan", "1991", "90s", ["romantic","sad"], "ycj1FwxiZwc"),
  cbgSong("Ae Kash Ke Hum", "Kumar Sanu", "Kabhi Haan Kabhi Naa", "1994", "90s", ["romantic","nostalgic"], "Jtg2zyS_y_c"),
  cbgSong("Ghar Se Nikalte Hi", "Udit Narayan", "Papa Kehte Hain", "1996", "90s", ["romantic","nostalgic","safar"], "0NT-xmLX4tk"),

  /* 2000s */
  cbgSong("Zara Zara", "Bombay Jayashri", "Rehnaa Hai Terre Dil Mein", "2001", "00s", ["romantic","baarish","sukoon"], "6CXI5ZQgo7A"),
  cbgSong("Sach Keh Raha Hai Deewana", "KK", "Rehnaa Hai Terre Dil Mein", "2001", "00s", ["sad","romantic"], "kp-Bqr1Gtyw"),
  cbgSong("Dil Ko Tumse Pyaar Hua", "Roop Kumar Rathod", "Rehnaa Hai Terre Dil Mein", "2001", "00s", ["romantic","sukoon"], "XcMy3lyDaQg"),
  cbgSong("Aankhon Mein Teri", "KK", "Om Shanti Om", "2007", "00s", ["romantic","sukoon"], "7KKVb0_IdD4"),
  cbgSong("Ajab Si", "KK", "Om Shanti Om", "2007", "00s", ["romantic","shaam"], "2drIKUOCZxU"),
  cbgSong("Tu Hi Meri Shab Hai", "KK", "Gangster", "2006", "00s", ["romantic","shaam"], "mWBvudKcByg"),
  cbgSong("Labon Ko", "KK", "Bhool Bhulaiyaa", "2007", "00s", ["romantic","shaam"], "XG8XskoJz1I"),
  cbgSong("Beete Lamhein", "KK", "The Train", "2007", "00s", ["sad","nostalgic"], "UlacMvx_VYk"),
  cbgSong("Khuda Jaane", "KK, Shilpa Rao", "Bachna Ae Haseeno", "2008", "00s", ["romantic","safar"], "cmMiyZaSELo"),
  cbgSong("Tujh Mein Rab Dikhta Hai", "Roop Kumar Rathod", "Rab Ne Bana Di Jodi", "2008", "00s", ["romantic","sukoon"], "qoq8B8ThgEM"),
  cbgSong("Haule Haule", "Sukhwinder Singh", "Rab Ne Bana Di Jodi", "2008", "00s", ["romantic","sukoon"], "XgdY_s1LsZc"),
  cbgSong("Main Agar Kahoon", "Sonu Nigam, Shreya Ghoshal", "Om Shanti Om", "2007", "00s", ["romantic","sukoon"], "DAYszemgPxc"),
  cbgSong("Abhi Mujh Mein Kahin", "Sonu Nigam", "Agneepath", "2012", "10s", ["sad","sukoon"], "oWKgpB2zpgw"),
  cbgSong("Suraj Hua Maddham", "Sonu Nigam, Alka Yagnik", "Kabhi Khushi Kabhie Gham", "2001", "00s", ["romantic","sukoon"], "L0zKs8i7Nc8"),
  cbgSong("Kal Ho Naa Ho", "Sonu Nigam", "Kal Ho Naa Ho", "2003", "00s", ["sad","nostalgic"], "g0eO74UmRBs"),
  cbgSong("Main Hoon Na", "Sonu Nigam, Shreya Ghoshal", "Main Hoon Na", "2004", "00s", ["romantic","nostalgic"], "DIJW7rWPkSw"),
  cbgSong("Tumse Milke Dil Ka", "Sonu Nigam, Sabri Brothers", "Main Hoon Na", "2004", "00s", ["romantic"], "mXkbWKr5ovU"),
  cbgSong("Tanhayee", "Sonu Nigam", "Dil Chahta Hai", "2001", "00s", ["sad","nostalgic"], "ZkwaiIGoyT4"),
  cbgSong("Iktara", "Kavita Seth", "Wake Up Sid", "2009", "00s", ["romantic","sukoon"], "fSS_R91Nimw"),
  cbgSong("Tum Se Hi", "Mohit Chauhan", "Jab We Met", "2007", "00s", ["romantic","safar"], "mt9xg0mmt28"),
  cbgSong("Yeh Dooriyan", "Mohit Chauhan", "Love Aaj Kal", "2009", "00s", ["sad","safar"], "kPtn26x8TZM"),
  cbgSong("Masakali", "Mohit Chauhan", "Delhi-6", "2009", "00s", ["safar","sukoon"], "SS3lIQdKP-A"),
  cbgSong("Pee Loon", "Mohit Chauhan", "Once Upon a Time in Mumbaai", "2010", "10s", ["romantic","baarish"], "D8XFTglfSMg"),
  cbgSong("Phir Se Ud Chala", "Mohit Chauhan", "Rockstar", "2011", "10s", ["safar","sukoon"], "2mWaqsC3U7k"),
  cbgSong("Tum Ho", "Mohit Chauhan, Suzanne D'Mello", "Rockstar", "2011", "10s", ["romantic","sukoon"], "VqFn3FvVjk4"),
  cbgSong("Kun Faya Kun", "A.R. Rahman, Javed Ali, Mohit Chauhan", "Rockstar", "2011", "10s", ["sukoon","safar"], "T94PHkuydcw"),
  cbgSong("Tera Hone Laga Hoon", "Atif Aslam, Alisha Chinai", "Ajab Prem Ki Ghazab Kahani", "2009", "00s", ["romantic"], "useznoRhrWU"),
  cbgSong("Pehli Nazar Mein", "Atif Aslam", "Race", "2008", "00s", ["romantic"], "JBCx0QyP8VQ"),
  cbgSong("Tu Jaane Na", "Atif Aslam", "Ajab Prem Ki Ghazab Kahani", "2009", "00s", ["romantic","sad"], "FA_J8XwpCaQ"),
  cbgSong("Tere Liye", "Atif Aslam, Shreya Ghoshal", "Prince", "2010", "10s", ["romantic","sad"], "AlvUuGJccKs"),
  cbgSong("Aadat", "Atif Aslam", "Kalyug", "2005", "00s", ["sad","shaam"], "e5LShHAE03A"),
  cbgSong("Woh Lamhe Woh Baatein", "Atif Aslam", "Zeher", "2005", "00s", ["sad","nostalgic"], "FLKxnL7KwHw"),
  cbgSong("Doorie", "Atif Aslam", "Doorie", "2006", "00s", ["sad","shaam"], "hP2p-yH1tGU"),
  cbgSong("Tere Bin", "Atif Aslam", "Bas Ek Pal", "2006", "00s", ["romantic","sad"], "yIrU21hoHys"),
  cbgSong("Aao Milo Chalo", "Shaan, Ustad Sultan Khan", "Jab We Met", "2007", "00s", ["safar","romantic"], "Mo5tQDcs__g"),
  cbgSong("Jab Se Tere Naina", "Shaan", "Saawariya", "2007", "00s", ["romantic","sukoon"], "3XtUEgQLI5Y"),
  cbgSong("Chand Sifarish", "Shaan, Kailash Kher", "Fanaa", "2006", "00s", ["romantic"], "zWEOx7TSM6I"),
  cbgSong("Kaho Naa Pyaar Hai", "Udit Narayan, Alka Yagnik", "Kaho Naa Pyaar Hai", "2000", "00s", ["romantic","nostalgic"], "-LESbtPT8uw"),
  cbgSong("Na Tum Jaano Na Hum", "Lucky Ali, Ramya", "Kaho Naa Pyaar Hai", "2000", "00s", ["romantic","sukoon"], "eSxo4l-epv8"),
  cbgSong("Ek Pal Ka Jeena", "Lucky Ali", "Kaho Naa Pyaar Hai", "2000", "00s", ["nostalgic"], "aGbPyM6lzBs"),
  cbgSong("Aa Bhi Ja Aa Bhi Ja", "Lucky Ali", "Sur", "2002", "00s", ["romantic","sad","sukoon"], "2OssKfYvVys"),
  cbgSong("Maula Mere Maula", "Roop Kumar Rathod", "Anwar", "2007", "00s", ["romantic","sukoon"], "fxfezWYW39M"),
  cbgSong("Jashn-E-Bahaaraa", "Javed Ali", "Jodhaa Akbar", "2008", "00s", ["romantic","sukoon"], "4h1WFyOQv0Y"),
  cbgSong("Tere Naina", "Shankar Mahadevan, Shreya Ghoshal", "My Name Is Khan", "2010", "10s", ["romantic","sukoon"]),
  cbgSong("Shukran Allah", "Sonu Nigam, Shreya Ghoshal, Salim Merchant", "Kurbaan", "2009", "00s", ["romantic","sukoon"], "z_B0PF8Ug00"),
  cbgSong("Aao Na", "Sadhana Sargam, Udit Narayan", "Kyun! Ho Gaya Na...", "2004", "00s", ["romantic","baarish"], "_TDmRLOqWws"),
  cbgSong("Bol Na Halke Halke", "Rahat Fateh Ali Khan, Mahalakshmi Iyer", "Jhoom Barabar Jhoom", "2007", "00s", ["romantic","sukoon"], "jXwg9l9D51A"),
  cbgSong("Aaj Din Chadheya", "Rahat Fateh Ali Khan", "Love Aaj Kal", "2009", "00s", ["romantic","sukoon"], "lhx8YSbrI6A"),
  cbgSong("Mann Ki Lagan", "Rahat Fateh Ali Khan", "Paap", "2003", "00s", ["romantic","sad"], "jUDP6LmgcCE"),
  cbgSong("O Re Piya", "Rahat Fateh Ali Khan", "Aaja Nachle", "2007", "00s", ["romantic","sukoon"], "iv7lcUkFVSc"),
  cbgSong("Teri Ore", "Rahat Fateh Ali Khan, Shreya Ghoshal", "Singh Is Kinng", "2008", "00s", ["romantic","sukoon"], "GLEx6bhPu7s"),

  /* 2010s */
  cbgSong("Tum Hi Ho", "Arijit Singh", "Aashiqui 2", "2013", "10s", ["romantic","sad"], "81qmmlsIE3k"),
  cbgSong("Chahun Main Ya Naa", "Arijit Singh, Palak Muchhal", "Aashiqui 2", "2013", "10s", ["romantic"], "II7ttbkotA0"),
  cbgSong("Hum Mar Jayenge", "Arijit Singh, Tulsi Kumar", "Aashiqui 2", "2013", "10s", ["romantic","sad"], "ky6nCXpDtlo"),
  cbgSong("Sun Raha Hai", "Ankit Tiwari", "Aashiqui 2", "2013", "10s", ["sad","romantic"], "tQL-gx7PeBc"),
  cbgSong("Agar Tum Saath Ho", "Alka Yagnik, Arijit Singh", "Tamasha", "2015", "10s", ["sad","romantic"], "sK7riqg2mr4"),
  cbgSong("Phir Le Aya Dil", "Arijit Singh", "Barfi!", "2012", "10s", ["romantic","sad","sukoon"], "k6BnSIs3XUQ"),
  cbgSong("Kabira", "Arijit Singh, Harshdeep Kaur", "Yeh Jawaani Hai Deewani", "2013", "10s", ["sad","safar"], "jJ4AsIV1FDI"),
  cbgSong("Ilahi", "Arijit Singh", "Yeh Jawaani Hai Deewani", "2013", "10s", ["safar","sukoon"], "hG7dg7dX4hg"),
  cbgSong("Mast Magan", "Arijit Singh, Chinmayi", "2 States", "2014", "10s", ["romantic","sukoon"], "fXRvluHnjxE"),
  cbgSong("Samjhawan", "Arijit Singh, Shreya Ghoshal", "Humpty Sharma Ki Dulhania", "2014", "10s", ["romantic","sad"], "wO5j3lv_9Fs"),
  cbgSong("Muskurane", "Arijit Singh", "CityLights", "2014", "10s", ["romantic","sad"], "HQ4Ox7mLqds"),
  cbgSong("Hamari Adhuri Kahani", "Arijit Singh", "Hamari Adhuri Kahani", "2015", "10s", ["sad","romantic"], "f3FFOBrMmdg"),
  cbgSong("Khamoshiyan", "Arijit Singh", "Khamoshiyan", "2015", "10s", ["romantic","shaam"], "Mv3SZDP7QUo"),
  cbgSong("Soch Na Sake", "Arijit Singh, Tulsi Kumar", "Airlift", "2016", "10s", ["romantic","sad"], "MRtRcTfszjY"),
  cbgSong("Ae Dil Hai Mushkil", "Arijit Singh", "Ae Dil Hai Mushkil", "2016", "10s", ["sad","romantic"], "6FURuLYrR_Q"),
  cbgSong("Channa Mereya", "Arijit Singh", "Ae Dil Hai Mushkil", "2016", "10s", ["sad","sukoon"], "284Ov7ysmfA"),
  cbgSong("Enna Sona", "Arijit Singh", "OK Jaanu", "2017", "10s", ["romantic","sukoon"], "mrdRHsIkK_c"),
  cbgSong("Hawayein", "Arijit Singh", "Jab Harry Met Sejal", "2017", "10s", ["romantic","safar"], "lBACSadCKaQ"),
  cbgSong("Phir Bhi Tumko Chaahunga", "Arijit Singh, Shashaa Tirupati", "Half Girlfriend", "2017", "10s", ["romantic","sad"], "cO02qJw6skA"),
  cbgSong("Qaafirana", "Arijit Singh, Nikhita Gandhi", "Kedarnath", "2018", "10s", ["romantic","safar"], "ZmcBC9-wAXM"),
  cbgSong("Ve Maahi", "Arijit Singh, Asees Kaur", "Kesari", "2019", "10s", ["romantic","sukoon"], "j6muwUGdvXw"),
  cbgSong("Tera Yaar Hoon Main", "Arijit Singh", "Sonu Ke Titu Ki Sweety", "2018", "10s", ["nostalgic","sad"], "EatzcaVJRMs"),
  cbgSong("Kaise Mujhe", "Benny Dayal, Shreya Ghoshal", "Ghajini", "2008", "00s", ["romantic","sad"], "OJVKIvKFmWk"),
  cbgSong("Saibo", "Shreya Ghoshal, Tochi Raina", "Shor in the City", "2011", "10s", ["romantic","sukoon"], "GtNrQy90Ih4"),
  cbgSong("Bahara", "Shreya Ghoshal, Sona Mohapatra", "I Hate Luv Storys", "2010", "10s", ["romantic","sukoon"], "7N74i_rAfFE"),
  cbgSong("Manwa Laage", "Shreya Ghoshal, Arijit Singh", "Happy New Year", "2014", "10s", ["romantic"], "d8IT-16kA8M"),
  cbgSong("Zehnaseeb", "Chinmayi, Shekhar Ravjiani", "Hasee Toh Phasee", "2014", "10s", ["romantic","sukoon"], "KLYwt0YmQw8"),
  cbgSong("Ishq Wala Love", "Shekhar Ravjiani, Salim Merchant, Neeti Mohan", "Student of the Year", "2012", "10s", ["romantic","sukoon"], "VmH8tELQ3aE"),
  cbgSong("Naina", "Arijit Singh", "Dangal", "2016", "10s", ["sad","nostalgic"], "yXbeYaVQ8JY"),
  cbgSong("Jiyein Kyun", "Papon", "Dum Maaro Dum", "2011", "10s", ["sad","shaam"], "sJW37INWnYk"),
  cbgSong("Moh Moh Ke Dhaage", "Papon, Monali Thakur", "Dum Laga Ke Haisha", "2015", "10s", ["romantic","sukoon"]),
  cbgSong("Kaun Mera", "Papon", "Special 26", "2013", "10s", ["romantic","sad"], "j8naefuRSbA"),
  cbgSong("Humnava", "Papon", "Hamari Adhuri Kahani", "2015", "10s", ["sad","romantic"], "ktPD6TMovxs"),
  cbgSong("Tu Kisi Rail Si", "Swanand Kirkire", "Masaan", "2015", "10s", ["romantic","sukoon"], "bKyhc18RCho"),
  cbgSong("Ikk Kudi", "Shahid Mallya", "Udta Punjab", "2016", "10s", ["sad","sukoon"], "cyKZXbxx2lc"),
  cbgSong("Dariya", "Arko", "Baar Baar Dekho", "2016", "10s", ["romantic","sukoon"], "C16EMv_J02w"),
  cbgSong("Nazm Nazm", "Arko", "Bareilly Ki Barfi", "2017", "10s", ["romantic","sukoon"], "RFx4g4GunYw"),
  cbgSong("Kho Gaye Hum Kahan", "Jasleen Royal, Prateek Kuhad", "Baar Baar Dekho", "2016", "10s", ["nostalgic","sukoon"], "as6gP05d_d4"),
  cbgSong("Ranjha", "B Praak, Jasleen Royal", "Shershaah", "2021", "20s", ["romantic","sad"], "V7LwfY5U5WI"),
  cbgSong("Baarish", "Ash King, Shashaa Tirupati", "Half Girlfriend", "2017", "10s", ["baarish","romantic"], "u6p6dubzHAc"),
  cbgSong("Baarish", "Mohammed Irfan, Gajendra Verma", "Yaariyan", "2014", "10s", ["baarish","romantic"], "IA2SN1QQbp8"),
  cbgSong("Sawan Aaya Hai", "Arijit Singh", "Creature 3D", "2014", "10s", ["baarish","romantic"], "UPxKI6pgyBQ"),
  cbgSong("Kabhi Jo Baadal Barse", "Arijit Singh", "Jackpot", "2013", "10s", ["baarish","romantic","sad"], "CXxkOAE1gPw"),
  cbgSong("Dekha Hazaro Dafaa", "Arijit Singh, Palak Muchhal", "Rustom", "2016", "10s", ["romantic","sukoon"], "NzijbnP6B0w"),

  /* Newer */
  cbgSong("Apna Bana Le", "Arijit Singh", "Bhediya", "2022", "20s", ["romantic","sukoon"], "3pz_bHeZLkg"),
  cbgSong("O Maahi", "Arijit Singh", "Dunki", "2023", "20s", ["romantic","safar"], "Etkd-07gnxM"),
  cbgSong("Sajni", "Arijit Singh", "Laapataa Ladies", "2024", "20s", ["romantic","sad"], "k3g_WjLCsXM"),
  cbgSong("Tere Vaaste", "Varun Jain, Sachin-Jigar, Shadab Faridi, Altamash Faridi", "Zara Hatke Zara Bachke", "2023", "20s", ["romantic"], "g5WZLO8BAC8"),
  cbgSong("Chaleya", "Arijit Singh, Shilpa Rao", "Jawan", "2023", "20s", ["romantic","sukoon"], "VAdGW7QDJiU"),
  cbgSong("Tere Hawaale", "Arijit Singh, Shilpa Rao", "Laal Singh Chaddha", "2022", "20s", ["romantic","sad"], "KUpwupYj_tY"),
  cbgSong("Phir Aur Kya Chahiye", "Arijit Singh", "Zara Hatke Zara Bachke", "2023", "20s", ["romantic","sukoon"], "PR_mFnjFidk"),
  cbgSong("Akhiyaan Gulaab", "Mitraz", "Teri Baaton Mein Aisa Uljha Jiya", "2024", "20s", ["romantic"], "r-BAhGM-dmA"),
  cbgSong("Husn", "Anuv Jain", "Husn", "2023", "20s", ["romantic","sad","sukoon"], "gJLVTKhTnog"),
  cbgSong("Jo Tum Mere Ho", "Anuv Jain", "Jo Tum Mere Ho", "2024", "20s", ["romantic","sukoon"], "ilNt2bikxDI"),
  cbgSong("Aankhon Se Batana", "Dikshant", "Aankhon Se Batana", "2022", "20s", ["romantic","sukoon"], "2vKMY75kvjI"),
  cbgSong("Kasoor", "Prateek Kuhad", "Kasoor", "2020", "20s", ["romantic","sad","sukoon"], "BmUe3-sfr7E"),
  cbgSong("Baarishein", "Anuv Jain", "Baarishein", "2018", "10s", ["baarish","romantic","sukoon"], "PJWemSzExXs"),
  cbgSong("Alag Aasmaan", "Anuv Jain", "Alag Aasmaan", "2020", "20s", ["safar","sad","sukoon"], "vA86QFrXoho"),
  cbgSong("Gul", "Anuv Jain", "Gul", "2021", "20s", ["romantic","sad","sukoon"], "SmaY7RfBgas"),
  cbgSong("Kahani Suno 2.0", "Kaifi Khalil", "Kahani Suno 2.0", "2022", "20s", ["romantic","sad"], "_XBVWlI8TsQ"),
  cbgSong("Heeriye", "Jasleen Royal, Arijit Singh", "Heeriye", "2023", "20s", ["romantic","sukoon"], "RLzC55ai0eo"),
  cbgSong("O Bedardeya", "Arijit Singh", "Tu Jhoothi Main Makkaar", "2023", "20s", ["sad","romantic"], "EdftT8GMU1U"),
  cbgSong("Arz Kiya Hai", "Anuv Jain", "Arz Kiya Hai - Coke Studio Bharat", "2025", "20s", ["romantic","sukoon"], "bP8ATWCvqzw"),
  cbgSong("Bairan", "Banjaare", "Bairan", "2026", "20s", ["sad","sukoon"], "oafxkMv4xnc"),

  /* Additional Romantic / 90s–2000s */
  cbgSong("Tune Zindagi Mein", "Udit Narayan", "Humraaz", "2002", "00s", ["romantic","sad"], "PjYSNHGbERs"),
  cbgSong("Hum Apni Taraf Se", "Kumar Sanu, Alka Yagnik", "Ansh: The Deadly Part", "2002", "00s", ["romantic","sad"], "6KTS5HpwK0E"),
  cbgSong("Jo Bhi Kasmein", "Udit Narayan, Alka Yagnik", "Raaz", "2002", "00s", ["romantic","sad"], "Mje4yC8NG_s"),
  cbgSong("Kitna Pyaara Hai", "Udit Narayan, Alka Yagnik", "Raaz", "2002", "00s", ["romantic"], "fPgBPqdR7-c"),
  cbgSong("Main Agar Saamne", "Abhijeet, Alka Yagnik", "Raaz", "2002", "00s", ["romantic","sad"], "KtqPRxTAbYQ"),
  cbgSong("Itna Main Chaahun Tujhe", "Udit Narayan, Alka Yagnik", "Raaz", "2002", "00s", ["romantic","sad"], "hR8AUj1J3kk"),
  cbgSong("Din Ne Ye Kaha Hai Dil Se", "Udit Narayan, Alka Yagnik", "Dhadkan", "2000", "00s", ["romantic","sad"], "ze9EhyeE9-4"),
  cbgSong("Dulhe Ka Sehra", "Nusrat Fateh Ali Khan", "Dhadkan", "2000", "00s", ["romantic","nostalgic"], "iZAv9zDeFSc"),
  cbgSong("Aksar Is Duniya Mein", "Alka Yagnik", "Dhadkan", "2000", "00s", ["romantic","nostalgic"], "-u1YYyRmmsc"),
  cbgSong("Resham Si Hain Yeh Hawayein", "Udit Narayan", "Mere Yaar Ki Shaadi Hai", "2002", "00s", ["romantic","sukoon"]),
  cbgSong("Ek Ladki Ki Tumhe", "Udit Narayan, Alka Yagnik", "Mere Yaar Ki Shaadi Hai", "2002", "00s", ["romantic"], "QaOe6GKw5Ic"),
  cbgSong("Mere Yaar Ki Shaadi Hai", "Udit Narayan, Sonu Nigam, Alka Yagnik", "Mere Yaar Ki Shaadi Hai", "2002", "00s", ["romantic","nostalgic"], "guHHhEUYAQ4"),
  cbgSong("Taaron Ka Chamakta Gehna Ho", "Bali Brahmbhatt, Udit Narayan", "Hum Tumhare Hain Sanam", "2002", "00s", ["romantic","nostalgic"], "GN8pRrHdzHY"),
  cbgSong("Taal Se Taal Mila", "Alka Yagnik, Udit Narayan", "Taal", "1999", "90s", ["romantic","baarish"], "dfghBD0hC9I"),
  cbgSong("Pehli Pehli Baar", "Kumar Sanu, Alka Yagnik", "Sirf Tum", "1999", "90s", ["romantic","nostalgic"], "cBGDDBHN22U"),
  cbgSong("Dilbar Dilbar", "Alka Yagnik", "Sirf Tum", "1999", "90s", ["romantic","nostalgic"], "KvWylZjOrYs"),
  cbgSong("Panchhi Sur Mein Gaate Hain", "Udit Narayan", "Sirf Tum", "1999", "90s", ["romantic","sukoon"], "Fl4ieJvjC60"),
  cbgSong("Ek Mulaqat Zaroori Hai", "Sabri Brothers", "Sirf Tum", "1999", "90s", ["romantic","sad"], "qKpnmFiCTSY"),
  cbgSong("Tere Naam", "Udit Narayan, Alka Yagnik", "Tere Naam", "2003", "00s", ["romantic","sad"], "OMoU0Pfibc4"),
  cbgSong("Tere Naam (Sad Version)", "Udit Narayan", "Tere Naam", "2003", "00s", ["sad","romantic"], "L7r_roRQMl8"),
  cbgSong("Tune Saath Jo Mera Chhoda", "Udit Narayan, Raghav", "Tere Naam", "2003", "00s", ["sad","romantic"], "F5KtNSMRAfM"),
  cbgSong("Kyon Kisi Ko", "Udit Narayan", "Tere Naam", "2003", "00s", ["sad"], "iCZfjggJg3M"),
  cbgSong("Man Basia", "Alka Yagnik", "Tere Naam", "2003", "00s", ["romantic","sukoon"], "7v5F-t1z5ts"),
  cbgSong("Galliyan", "Ankit Tiwari", "Ek Villain", "2014", "10s", ["romantic","sad"], "FxAG_11PzCk"),
  cbgSong("Banjaara", "Mohammed Irfan", "Ek Villain", "2014", "10s", ["romantic","sad"], "0NFxcNheoLc"),
  cbgSong("Zaroorat", "Mustafa Zahid", "Ek Villain", "2014", "10s", ["sad"], "VMEXKJbsUmE"),
  cbgSong("To Phir Aao", "Mustafa Zahid", "Awarapan", "2007", "00s", ["sad","romantic"], "h5-Kq9k3zeo"),
  cbgSong("Tera Mera Rishta", "Mustafa Zahid", "Awarapan", "2007", "00s", ["sad","romantic"], "0J0HZrDvbjY"),
  cbgSong("Kaun Tujhe", "Palak Muchhal", "M.S. Dhoni: The Untold Story", "2016", "10s", ["romantic","sad"], "atVof3pjT-I"),
  cbgSong("Saari Raat Teri Yaad", "Udit Narayan, Alka Yagnik", "Footpath", "2003", "00s", ["romantic","sad"], "1KvCHSlK9vc"),
  cbgSong("Zara Dekh Mera Deewanapan", "Udit Narayan, Alka Yagnik", "Footpath", "2003", "00s", ["romantic","sad"], "iDrNusV2bE8"),
  cbgSong("Falak Tak Chal Saath Mere", "Udit Narayan, Mahalakshmi Iyer", "Tashan", "2008", "00s", ["romantic","safar"], "vr8RaNuWjWc"),
  cbgSong("Jeena Sirf Mere Liye", "Babul Supriyo, Alka Yagnik", "Jeena Sirf Merre Liye", "2002", "00s", ["romantic","sad"], "I6pJI0JF8EA"),

  /* Emraan Hashmi-associated songs */
  cbgSong("Dil Ibadat", "KK", "Tum Mile", "2009", "00s", ["romantic","sad"], "bCgBLKPE35Y"),
  cbgSong("Deewana Kar Raha Hai", "Javed Ali", "Raaz 3", "2012", "10s", ["romantic","sad"], "uIvZHM9J-Rw"),
  cbgSong("Zara Sa", "KK", "Jannat", "2008", "00s", ["romantic","shaam"], "ZsAOnmByy38"),
  cbgSong("Woh Lamhe", "Atif Aslam", "Jal Pari", "2004", "00s", ["sad","nostalgic"]),
  cbgSong("Haal-E-Dil", "Harshit Saxena", "Murder 2", "2011", "10s", ["sad","romantic"], "acdKE2hja7w"),
  cbgSong("Phir Mohabbat", "Mohammed Irfan, Arijit Singh, Saim Bhat", "Murder 2", "2011", "10s", ["sad","romantic"], "v71SiUe0KYY"),
  cbgSong("Haan Tu Hai", "KK", "Jannat", "2008", "00s", ["romantic","sad"], "V1fbOsHBlZE"),
  cbgSong("Tu Hi Haqeeqat", "Javed Ali", "Tum Mile", "2009", "00s", ["romantic","sad"], "BKbnmLH8UAo"),

  /* Tumsa Nahin Dekha */
  cbgSong("Bheed Mein", "Udit Narayan, Shreya Ghoshal", "Tumsa Nahin Dekha: A Love Story", "2004", "00s", ["romantic","sad"], "Eu9LPo0gqeQ"),
  cbgSong("Woh Humse Khafa Hain", "Udit Narayan, Shreya Ghoshal", "Tumsa Nahin Dekha: A Love Story", "2004", "00s", ["romantic","sad"], "JkAifHDj0fE"),
  cbgSong("Dhanak Ka Rang", "Shreya Ghoshal", "Tumsa Nahin Dekha: A Love Story", "2004", "00s", ["romantic","sukoon"], "hYKY4oLbs2Q"),

  /* Additional Classics */
  cbgSong("Bulleya", "Amit Mishra, Shilpa Rao", "Ae Dil Hai Mushkil", "2016", "10s", ["sad","romantic"], "wTgrZE9RWNY"),
  cbgSong("Aaj Mausam Bada Beimaan Hai", "Mohammed Rafi", "Loafer", "1973", "70s", ["old-gold","baarish","nostalgic"], "opABbsJaRLQ"),
  cbgSong("Mere Samne Wali Khidki Mein", "Kishore Kumar", "Padosan", "1968", "60s", ["romantic","old-gold"], "XINI9JtypMw"),
  cbgSong("Yeh Raaten Yeh Mausam", "Asha Bhosle, Kishore Kumar", "Dilli Ka Thug", "1958", "50s", ["romantic","shaam","old-gold"], "ouNb2s33ioQ"),

  /* Kasoor — complete original soundtrack */
  cbgSong("Zindagi Ban Gaye Ho Tum", "Alka Yagnik, Udit Narayan", "Kasoor", "2001", "00s", ["romantic","sukoon"], "gejEimJIdWc"),
  cbgSong("Koi To Saathi Chahiye", "Kumar Sanu", "Kasoor", "2001", "00s", ["romantic","sad"], "9ylzcAwzROs"),
  cbgSong("Dil Mera Tod Diya", "Alka Yagnik", "Kasoor", "2001", "00s", ["sad"], "TuxveFT--1U"),
  cbgSong("Kal Raat Ho Gayee", "Alka Yagnik, Kumar Sanu", "Kasoor", "2001", "00s", ["romantic","shaam"], "u5JIUfrpzY8"),
  cbgSong("Kitni Bechain Hoke", "Alka Yagnik, Udit Narayan", "Kasoor", "2001", "00s", ["romantic"], "ZHcxorEN7k4"),
  cbgSong("Mohabbat Ho Na Jaye (Dekha Jo Tumko)", "Alka Yagnik, Kumar Sanu", "Kasoor", "2001", "00s", ["romantic","sukoon"], "SbnpXVOzf6g"),

  /* Muskaan — complete original soundtrack */
  cbgSong("Ishq Hasata Hai", "Sonu Nigam, Anuradha Paudwal", "Muskaan", "2003", "00s", ["romantic","sad"], "p5jvLT7wod4"),
  cbgSong("Jaaneman Chupke Chupke", "Udit Narayan, Alka Yagnik", "Muskaan", "2003", "00s", ["romantic"], "FNImjHOLS_E"),
  cbgSong("Jaaneman Chupke Chupke-2", "Anuradha Paudwal", "Muskaan", "2003", "00s", ["romantic","sukoon"], "RA8iE6XwI7E"),
  cbgSong("Jis Din Teri Meri Baatein", "Udit Narayan, Anuradha Paudwal", "Muskaan", "2003", "00s", ["romantic"], "o2ZrGUWiavY"),
  cbgSong("Kabhie Jaage Soye", "Udit Narayan, Anuradha Paudwal", "Muskaan", "2003", "00s", ["romantic","sukoon"], "CnIqESltgwA"),
  cbgSong("Nach Punjaban Nachle", "Sonu Nigam, Anuradha Paudwal", "Muskaan", "2003", "00s", ["romantic","nostalgic"], "petIS6mS-0o"),
  cbgSong("Nami Danam", "Shaan, Alka Yagnik", "Muskaan", "2003", "00s", ["romantic","sukoon"], "6DK0htUj_Us"),
  cbgSong("Woh Ho Tum", "Sonu Nigam, Anuradha Paudwal", "Muskaan", "2003", "00s", ["romantic"], "LCl2_jiPtpg"),
  cbgSong("Woh Ho Tum", "Sonu Nigam, Shreya Ghoshal", "Muskaan", "2003", "00s", ["romantic","sukoon"], "utTZFVaQnlA"),
  cbgSong("Woh Ho Tum (Sad)", "Sonu Nigam", "Muskaan", "2003", "00s", ["sad","romantic"], "tALSTPQUMf8"),
  cbgSong("Yaad Aayee", "Adnan Sami", "Muskaan", "2003", "00s", ["sad","nostalgic"], "9AgIuLJ33lY"),

  /* =========================================================================
   * KANNADA PLAYLIST (101 VERIFIED UNIQUE RECORDINGS)
   * Source: Independent Verification Report
   * ========================================================================= */

  /* Kannada Classics & 1970s–1980s */
  cbgSong("Nee Mudida Mallige", "P. B. Sreenivos, P. Susheela", "Gandhinagara", "1968", "60s", ["romantic","old-gold","sukoon"], "0o9a2Xk7k30", "kannada"),
  cbgSong("Nee Bandu Ninthaaga", "P. B. Sreenivos, P. Susheela", "Kasturi Nivasa", "1971", "70s", ["nostalgic","old-gold","sukoon"], "q66UaR8QJ_Q", "kannada"),
  cbgSong("Naa Ninna Mareyalaare", "Dr. Rajkumar, Vani Jairam", "Naa Ninna Mareyalaare", "1976", "70s", ["romantic","old-gold","nostalgic"], "FD3UN6dELZg", "kannada"),
  cbgSong("Nagunagutha Nee Baruve", "Dr. Rajkumar, S. Janaki", "Giri Kanye", "1977", "70s", ["romantic","old-gold","sukoon"], "P2f5gP5t1s0", "kannada"),
  cbgSong("Sangeethave Nee Nudiyuva Maathella", "P. B. Sreenivos, S. Janaki", "Olavu Gelavu", "1977", "70s", ["romantic","old-gold","shaam"], "s5R2_yP2g-c", "kannada"),
  cbgSong("Chinnada Mallige Hoove", "Dr. Rajkumar, S. Janaki", "Huliya Haalina Mevu", "1979", "70s", ["romantic","old-gold","sukoon"], "40h49dcIaxM", "kannada"),
  cbgSong("Kaalavannu Thadeyoru Yaaru", "K. J. Yesudas", "Kittu Puttu", "1977", "70s", ["nostalgic","old-gold","shaam"], "R9Z8c42v_hI", "kannada"),
  cbgSong("Naguva Nayana", "S. P. Balasubrahmanyam, S. Janaki", "Pallavi Anu Pallavi", "1983", "80s", ["romantic","sukoon","old-gold","shaam"], "kY_x5bZ-G68", "kannada"),
  cbgSong("Ee Roopave Shaapa Venu", "S. P. Balasubrahmanyam", "Seetha Ramu", "1979", "70s", ["sad","old-gold","nostalgic"], "fN4j7Kk8W3s", "kannada"),
  cbgSong("Nammooru Mysooru", "S. P. Balasubrahmanyam, S. Janaki", "Preethi Maadu Tamasshe Nodu", "1979", "70s", ["nostalgic","old-gold","safar"], "gZ7rV3kQ9Yw", "kannada"),

  /* Kannada 1990s */
  cbgSong("Mutthu Mutthu Neera Haniya", "S. P. Balasubrahmanyam, K. S. Chithra", "Nammoora Mandara Hoove", "1996", "90s", ["baarish","romantic","nostalgic","sukoon"], "kY0wzO0-Vw0", "kannada"),
  cbgSong("Ee Sundara Beladingala", "S. P. Balasubrahmanyam, K. S. Chithra", "Amruthavarshini", "1997", "90s", ["romantic","sukoon","shaam","baarish"], "k-a8n0d358M", "kannada"),
  cbgSong("Yele Hombisile", "S. P. Balasubrahmanyam", "Halunda Thavaru", "1994", "90s", ["sukoon","nostalgic","shaam"], "m7q751_rJ3A", "kannada"),
  cbgSong("O Gulabiye", "Dr. Rajkumar", "Om", "1995", "90s", ["sad","nostalgic","romantic"], "eLvUvuLr-fI", "kannada"),
  cbgSong("Suvvi Suvvi Saviyaada", "S. P. Balasubrahmanyam", "Laali", "1997", "90s", ["sukoon","nostalgic"], "l0Q8uW4vR7k", "kannada"),
  cbgSong("Muddina Hudugi Chanda", "S. P. Balasubrahmanyam, K. S. Chithra", "Rayaru Bandaru Mavana Manege", "1993", "90s", ["romantic","nostalgic"], "U0g8kO_3d5E", "kannada"),
  cbgSong("Sum Sumne", "L. N. Shastry", "A", "1998", "90s", ["romantic","nostalgic","sukoon"], "1cPSG6Lb0v8", "kannada"),
  cbgSong("Anuraaga Geethe", "S. P. Balasubrahmanyam, K. S. Chithra", "Anuraaga Geethe", "1994", "90s", ["romantic","nostalgic","sukoon"], "vW8fG0sK9zA", "kannada"),
  cbgSong("Nooru Janmaku", "Rajesh Krishnan", "America America", "1997", "90s", ["romantic","nostalgic","sukoon","safar"], "pFt58gtRgiM", "kannada"),

  /* Kannada 2000s */
  cbgSong("Olave Nannolave", "Sonu Nigam", "Laali Haadu", "2003", "00s", ["romantic","sukoon","nostalgic"], "Wks8AXdywpI", "kannada"),
  cbgSong("Ee Nanna Kannane", "Gurukiran, Nanditha", "Abhi", "2003", "00s", ["romantic","sukoon"], "pZ4kQ8wU2eR", "kannada"),
  cbgSong("Neene Neene", "Sonu Nigam, Shreya Ghoshal", "Ee Preethi Yeke Bhoomi Melide", "2007", "00s", ["romantic","sukoon","shaam"], "fG8qW3vY1zL", "kannada"),
  cbgSong("Nenapirali", "Chetan Sosca", "Nenapirali", "2005", "00s", ["nostalgic","sad","sukoon"], "k8W0vQ2mY4x", "kannada"),
  cbgSong("O Manase Manase", "K. J. Yesudas", "Gaja", "2008", "00s", ["sad","sukoon","shaam"], "xN3fL8qW0zU", "kannada"),
  cbgSong("Hoo Kanasa Jokali", "Sonu Nigam", "Inthi Ninna Preethiya", "2008", "00s", ["sad","sukoon","nostalgic","shaam"], "R96vS_rGg34", "kannada"),
  cbgSong("O Gunavantha", "Sonu Nigam, Shreya Ghoshal", "Jothe Jotheyali", "2006", "00s", ["romantic","sukoon","shaam"], "bTJHgrGZnS4", "kannada"),
  cbgSong("Neenu Avalagabahudu", "Rajesh Krishnan", "Joot", "2003", "00s", ["romantic","sukoon"], "tG0kW4vY7xQ", "kannada"),
  cbgSong("Ee Manasella Neene", "Rajesh Krishnan, Nanditha", "Monalisa", "2004", "00s", ["romantic","nostalgic"], "qW3vY1zLfG8", "kannada"),
  cbgSong("Kuch Kuch Anthide", "Krishna Beura, Sunitha", "Raaj The Showman", "2009", "00s", ["romantic","sukoon","shaam"], "yL9qW0vG4xZ", "kannada"),
  cbgSong("Avala Olave Chandu", "Rajesh Krishnan", "Chandu", "2002", "00s", ["romantic","sukoon"], "kQ2mY4xZ7wF", "kannada"),
  cbgSong("Dinavella Hasivilla", "Rajesh Krishnan, Nanditha", "Khushi", "2003", "00s", ["romantic","sukoon"], "wU2eRpZ4kQ8", "kannada"),
  cbgSong("Nodavalandava", "Kunal Ganjawala, Shreya Ghoshal", "Sevanthi Sevanthi", "2006", "00s", ["romantic","sukoon","shaam"], "uL4vR7kM8qW", "kannada"),
  cbgSong("Jothe Jotheyali", "S. P. Balasubrahmanyam, Sunitha", "Jothe Jotheyali", "2006", "00s", ["romantic","nostalgic","sukoon"], "yW1zLfG8qW3", "kannada"),
  cbgSong("Anisuthide", "Sonu Nigam", "Mungaru Male", "2006", "00s", ["baarish","sukoon","romantic","shaam"], "uchdYcbq7Ys", "kannada"),
  cbgSong("Madhura Pisumatige", "Mohit Chauhan, Shamitha Malnad", "Birugaali", "2009", "00s", ["romantic","sukoon","safar","shaam"], "nsVTVikFCOA", "kannada"),
  cbgSong("Aramage Idde Naanu", "Sonu Nigam, Shreya Ghoshal", "Gokula", "2009", "00s", ["romantic","sukoon","safar"], "gZ3kQ9wU2eR", "kannada"),
  cbgSong("Kushiyagide Eko Nannali", "Kunal Ganjawala", "Tajmahal", "2008", "00s", ["romantic","sukoon"], "VjqqvAxT9rk", "kannada"),
  cbgSong("Araluthiru", "Shreya Ghoshal", "Mungaru Male", "2006", "00s", ["baarish","romantic","sukoon","shaam"], "kYJvC8mK1OQ", "kannada"),
  cbgSong("Ivanu Geleyanalla", "Shreya Ghoshal", "Mungaru Male", "2006", "00s", ["romantic","sad","baarish","sukoon"], "6ATTRCxx9-4", "kannada"),
  cbgSong("Ninna Nodalentho", "Sonu Nigam, Shreya Ghoshal", "Mussanje Maatu", "2008", "00s", ["romantic","sukoon","shaam"], "6mnpoERBkYg", "kannada"),
  cbgSong("Ninnindale Ninnindale", "Sonu Nigam", "Milana", "2007", "00s", ["romantic","sukoon","safar","nostalgic"], "_00lANhPkKc", "kannada"),
  cbgSong("Mungaru Maleye", "Sonu Nigam", "Mungaru Male", "2006", "00s", ["baarish","nostalgic","sukoon","shaam"], "Fz6zKCrV2vg", "kannada"),
  cbgSong("Nee Sanihake Bandre", "Sonu Nigam", "Maleyali Jotheyali", "2009", "00s", ["baarish","romantic","sukoon","shaam"], "vR7kM8qW0zU", "kannada"),
  cbgSong("Ee Sanje Yaakagide", "Sonu Nigam", "Geleya", "2007", "00s", ["shaam","sukoon","romantic","sad"], "ivZYiVirkKc", "kannada"),
  cbgSong("Nee Nenedare", "Sonu Nigam", "Junglee", "2009", "00s", ["romantic","sukoon","baarish"], "ff3PgNcC_eY", "kannada"),
  cbgSong("Kavithe Kavithe", "Vijay Prakash", "Gaalipata", "2008", "00s", ["romantic","sukoon","shaam","nostalgic"], "dFlfdk-bJrQ", "kannada"),

  /* Kannada 2010s */
  cbgSong("Preethiya Hesare Neenu", "Raghu Dixit", "Happy New Year", "2017", "10s", ["sukoon","romantic","safar"], "rIPtyodvaJk", "kannada"),
  cbgSong("Sadaa Ninna Kannali", "Sonu Nigam, Shreya Ghoshal", "Bachchan", "2013", "10s", ["romantic","sukoon","shaam"], "lO3_U3wYlJ0", "kannada"),
  cbgSong("Hoovina Santhege", "Sonu Nigam, Shreya Ghoshal", "Lucky", "2012", "10s", ["romantic","sukoon","shaam"], "xW0zU4vR7kM", "kannada"),
  cbgSong("Ninna Snehadinda", "Shreya Ghoshal", "Mugulu Nage", "2017", "10s", ["sukoon","romantic","shaam","nostalgic"], "LeWQ1dyL658", "kannada"),
  cbgSong("Ondu Malebillu", "Armaan Malik, Shreya Ghoshal", "Chakravarthy", "2017", "10s", ["baarish","romantic","sukoon"], "Xv1NQFN9Kd8", "kannada"),
  cbgSong("Belageddu", "Vijay Prakash", "Kirik Party", "2016", "10s", ["sukoon","safar","nostalgic"], "ebz20FHrT44", "kannada"),
  cbgSong("Kareyole", "Inchara Rao", "Rangitaranga", "2015", "10s", ["baarish","sukoon","nostalgic","shaam"], "5Vj-g_p3UIs", "kannada"),
  cbgSong("Roopasi Sumsumne", "Vijay Prakash", "Mugulu Nage", "2017", "10s", ["romantic","sukoon","shaam"], "7TJN6kNDxQ8", "kannada"),
  cbgSong("Usire Usire", "Shaan, Shreya Ghoshal", "Hebbuli", "2017", "10s", ["romantic","sukoon","shaam"], "tW7vY3kQ9Zl", "kannada"),
  cbgSong("Chippinolagade", "Shreya Ghoshal", "Maasthigudi", "2017", "10s", ["romantic","sukoon","shaam"], "OPjrRU8r6aQ", "kannada"),
  cbgSong("Nee Nanna Olavina", "Ebisa", "Huliraya", "2017", "10s", ["sukoon","nostalgic","shaam"], "zLfG8qW3vY1", "kannada"),
  cbgSong("Bombe Helutaithe", "Vijay Prakash", "Raajakumara", "2017", "10s", ["nostalgic","sukoon","old-gold"], "sU14zKxP240", "kannada"),
  cbgSong("Sidila Bharava", "Ananya Bhat, Ravi Basrur", "K.G.F: Chapter 1", "2018", "10s", ["safar"], "qW4u2Y0mL7x", "kannada"),
  cbgSong("Hey Who Are You", "Bharath B. J.", "Kirik Party", "2016", "10s", ["safar"], "mZ1vEo0P7L4", "kannada"),
  cbgSong("Sojugada Soojumallige", "Ananya Bhat", "Sounds of Isha", "2019", "10s", ["sukoon","nostalgic","shaam","old-gold"], "gTk-xB3GSOg", "kannada"),
  cbgSong("Gaganave Baagi", "Shreya Ghoshal", "Sanju Weds Geetha", "2011", "10s", ["romantic","baarish","sukoon","shaam"], "bVaQL41j6ZY", "kannada"),
  cbgSong("Modala Maleyanthe", "Sonu Nigam, Shreya Ghoshal", "Mynaa", "2013", "10s", ["baarish","romantic","sukoon"], "pm0iMhkSe-o", "kannada"),
  cbgSong("Ninneya Nalumeya", "Shreya Ghoshal", "Pancharangi", "2010", "10s", ["romantic","sukoon","shaam"], "Pt1e68xoCxQ", "kannada"),
  cbgSong("Aalochane", "Shreya Ghoshal", "Romeo", "2012", "10s", ["romantic","sukoon"], "aGGyYYmfzTU", "kannada"),
  cbgSong("Yenendu Hesaridali", "Sonu Nigam, Shreya Ghoshal", "Anna Bond", "2012", "10s", ["romantic","sukoon","shaam"], "A6AwVskOCo8", "kannada"),
  cbgSong("Upavasa", "Sonu Nigam, Shreya Ghoshal", "Mr. and Mrs. Ramachari", "2014", "10s", ["romantic","sukoon","shaam"], "iPOCZdhEf28", "kannada"),
  cbgSong("Kanasalu", "Shreya Ghoshal", "Mungaru Male 2", "2016", "10s", ["romantic","baarish","sukoon"], "k6e-Ww_v8-Q", "kannada"),
  cbgSong("Matthe Maleyagide", "Sonu Nigam, Shreya Ghoshal", "Chakravarthy", "2017", "10s", ["baarish","romantic","sukoon","shaam"], "gB4ErkONc2w", "kannada"),
  cbgSong("Saaluthillave", "Vijay Prakash, Shreya Ghoshal", "Kotigobba 2", "2016", "10s", ["romantic","sukoon","shaam"], "yP6l5qS0c9g", "kannada"),
  cbgSong("Neenire Saniha", "Shreya Ghoshal", "Kirik Party", "2016", "10s", ["romantic","sukoon","shaam"], "1114_Nq-23E", "kannada"),
  cbgSong("Nodivalandava", "Armaan Malik, Shreya Ghoshal", "The Villain", "2018", "10s", ["romantic","sukoon"], "2hT_SXI8s64", "kannada"),
  cbgSong("Anisuthidhe", "Shreya Ghoshal", "99", "2019", "10s", ["sad","nostalgic","sukoon","shaam"], "Q8Q_D77dgzk", "kannada"),
  cbgSong("Summane Heege Ninnane", "Sonu Nigam, Shreya Ghoshal", "Amar", "2019", "10s", ["romantic","sukoon","safar","shaam"], "MRmhCQS9fIs", "kannada"),
  cbgSong("Naa Sanihake Innu", "Shreya Ghoshal", "99", "2019", "10s", ["nostalgic","sad","sukoon","shaam"], "fGF7iUkG8_A", "kannada"),
  cbgSong("Hrudayave Bayaside Ninnane", "Sonu Nigam", "Krishnan Love Story", "2010", "10s", ["romantic","sukoon","shaam","sad"], "Xh0YqJk9s7E", "kannada"),
  cbgSong("Paravashanadenu", "Sonu Nigam", "Paramathma", "2011", "10s", ["sukoon","safar","romantic","shaam"], "C7P7Z4YyO5g", "kannada"),
  cbgSong("Baanali Badalago Soorya", "Sonu Nigam", "Simpallaag Ond Love Story", "2013", "10s", ["romantic","sukoon","shaam"], "WOuUEZVFqG8", "kannada"),
  cbgSong("Gamanisu", "Sonu Nigam", "Mungaru Male 2", "2016", "10s", ["sad","sukoon","baarish","shaam"], "w9082JWVhjQ", "kannada"),
  cbgSong("Kanna Minche", "Sonu Nigam", "Victory", "2013", "10s", ["romantic","sukoon"], "QOMDi_Yw0ns", "kannada"),
  cbgSong("Yenammi Yenammi", "Vijay Prakash, Palak Muchhal", "Ayogya", "2018", "10s", ["romantic","sukoon","shaam"], "kGq_lS8R-e4", "kannada"),
  cbgSong("Ninthe Ninthe", "Vijay Prakash, Chinmayi", "Ninnindale", "2014", "10s", ["romantic","sukoon","safar"], "kYjXv73rC8Q", "kannada"),
  cbgSong("Gatiya Ilidu", "Vijay Prakash, B. Ajaneesh Loknath", "Ulidavaru Kandanthe", "2014", "10s", ["nostalgic","shaam","sukoon"], "kR2g3i1B5L0", "kannada"),
  cbgSong("Khali Quarter Batli", "Vijay Prakash", "Victory", "2013", "10s", ["nostalgic"], "zU4vR7kM8qW", "kannada"),
  cbgSong("Shaane Top Agavle", "Vijay Prakash", "Singa", "2019", "10s", ["romantic"], "qW0zU4vR7kM", "kannada"),
  cbgSong("Yavva Yavva", "Vijay Prakash", "Raambo 2", "2018", "10s", ["romantic","safar"], "pDsr6DJwFRw", "kannada"),
  cbgSong("Heege Doora", "Vijay Prakash", "99", "2019", "10s", ["sad","nostalgic","sukoon","shaam"], "j3d_QJ1t4y4", "kannada"),
  cbgSong("Ammi Ammi", "Vijay Prakash", "Preethiya Raayabhari", "2018", "10s", ["romantic","sukoon"], "vY1zLfG8qW3", "kannada"),
  cbgSong("Early Morning", "Vijay Prakash", "Dalapathi", "2018", "10s", ["romantic","sukoon"], "q8W0vQ2mY4x", "kannada"),

  /* Kannada 2020s */
  cbgSong("Dwapara", "Jaskaran Singh", "Krishnam Pranaya Sakhi", "2024", "20s", ["romantic","sukoon"], "C93Tcb9wJRE", "kannada"),
  cbgSong("Sapta Sagaradaache Ello Title Track", "Kapil Kapilan", "Sapta Sagaradaache Ello - Side A", "2023", "20s", ["baarish","romantic","sukoon","shaam","sad"], "F086X4G2P8c", "kannada"),
  cbgSong("Kadalanu Kaana Horatiro", "Charan Raj, Srilakshmi Belmannu", "Sapta Sagaradaache Ello - Side A", "2023", "20s", ["sukoon","shaam","safar","nostalgic"], "kYJmQe9W1dM", "kannada"),
  cbgSong("Kannu Hodiyaka", "Shreya Ghoshal", "Roberrt", "2021", "20s", ["romantic"], "wX0zU4vR7kM", "kannada"),
  cbgSong("Nannavale Nannavale", "Sonu Nigam", "Inspector Vikram", "2021", "20s", ["romantic","sukoon"], "nN4-k4hS8g4", "kannada"),
  cbgSong("Bombe Bombe", "Sonu Nigam", "Kranti", "2023", "20s", ["sukoon","nostalgic"], "kM8qW0zU4vR", "kannada"),
  cbgSong("Mayavi", "Sonu Nigam, Sanjith Hegde", "Bhoomi 2024", "2024", "20s", ["sukoon","shaam","safar"], "TMY1g8pAktk", "kannada"),
  cbgSong("Singara Siriye", "Vijay Prakash, Ananya Bhat", "Kantara", "2022", "20s", ["romantic","baarish","sukoon","safar"], "A88y857cO8Q", "kannada"),
  cbgSong("Pataki Poriyo", "Vijay Prakash, Anuradha Bhat", "Kotigobba 3", "2021", "20s", ["romantic"], "J4zjLb2MhoU", "kannada"),
  cbgSong("Devle Devle", "Vijay Prakash", "Gaalipata 2", "2022", "20s", ["nostalgic","safar"], "dhCIo7lEnsQ", "kannada"),
  cbgSong("Aane Maadi Heluteeni", "Vijay Prakash, Nihal Tauro", "Guru Shishyaru", "2022", "20s", ["romantic","sukoon"], "gNxQAa8NpQg", "kannada"),
  cbgSong("Udupi Hotelu", "Vijay Prakash", "Badava Rascal", "2021", "20s", ["nostalgic","safar"], "mY4xZ7wF0eL", "kannada")
];
